/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2010, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.audiomanager.client;

/**
 *
 * @author jp
 */
public class AudioProblemJFrame extends javax.swing.JFrame {

    AudioManagerClient client;

    /** Creates new form AudioProblemJFrame */
    public AudioProblemJFrame() {
        initComponents();
    }

    public AudioProblemJFrame(AudioManagerClient client) {
	this.client = client;
        initComponents();

	getRootPane().setDefaultButton(okButton);
    }

    private boolean ignoreProblem;

    public void setText(String problem) {
	if (ignoreProblem) {
	    return;
	}

	String pattern = "Softphone Problem: ";

	int ix = problem.indexOf(pattern);

	if (ix >= 0) {
	    problem = problem.substring(ix + pattern.length());
	}

	final String[] tokens = problem.split("[.]");

	String s = "";

	for (int i = 1; i < tokens.length; i++) {
	    s += tokens[i].trim() + "\n";
	}

	final String text = s;

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
		audioProblemLabel.setText(tokens[0].trim());

		if (tokens.length == 1) {
		    audioProblemTextArea.setText("No details.");
		} else {
		    audioProblemTextArea.setText(text);
		}

		setVisible(true);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        audioProblemLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        audioProblemTextArea = new javax.swing.JTextArea();
        reconfigureButton = new javax.swing.JButton();
        reconnectButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        ignoreButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jdesktop/wonderland/modules/audiomanager/client/resources/Bundle"); // NOI18N
        setTitle(bundle.getString("AudioProblemJFrame.title")); // NOI18N

        audioProblemLabel.setFont(audioProblemLabel.getFont().deriveFont(audioProblemLabel.getFont().getStyle() | java.awt.Font.BOLD));
        audioProblemLabel.setText(bundle.getString("AudioProblemJFrame.audioProblemLabel.text")); // NOI18N
        audioProblemLabel.setFocusable(false);
        audioProblemLabel.setRequestFocusEnabled(false);

        audioProblemTextArea.setBackground(new java.awt.Color(238, 238, 238));
        audioProblemTextArea.setColumns(1);
        audioProblemTextArea.setEditable(false);
        audioProblemTextArea.setLineWrap(true);
        audioProblemTextArea.setRows(3);
        audioProblemTextArea.setBorder(null);
        audioProblemTextArea.setFocusable(false);
        audioProblemTextArea.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(audioProblemTextArea);

        reconfigureButton.setText(bundle.getString("AudioProblemJFrame.reconfigureButton.text")); // NOI18N
        reconfigureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconfigureButtonActionPerformed(evt);
            }
        });

        reconnectButton.setText(bundle.getString("AudioProblemJFrame.reconnectButton.text")); // NOI18N
        reconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconnectButtonActionPerformed(evt);
            }
        });

        okButton.setText(bundle.getString("AudioProblemJFrame.okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        ignoreButton.setText(bundle.getString("AudioProblemJFrame.ignoreButton.text")); // NOI18N
        ignoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignoreButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .add(audioProblemLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(reconfigureButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(reconnectButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(ignoreButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(audioProblemLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(reconnectButton)
                    .add(ignoreButton)
                    .add(reconfigureButton))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reconfigureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconfigureButtonActionPerformed
	client.testAudio();
    }//GEN-LAST:event_reconfigureButtonActionPerformed

    private void reconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconnectButtonActionPerformed
        client.connectSoftphone();
    }//GEN-LAST:event_reconnectButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
	setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void ignoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreButtonActionPerformed
        ignoreProblem = true;
	setVisible(false);
    }//GEN-LAST:event_ignoreButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudioProblemJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel audioProblemLabel;
    private javax.swing.JTextArea audioProblemTextArea;
    private javax.swing.JButton ignoreButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JButton reconfigureButton;
    private javax.swing.JButton reconnectButton;
    // End of variables declaration//GEN-END:variables

}
