#!/bin/bash
# Asher Bond 2011
# configure make make install
# use <trunkdir> <branch1 branch2 branch3>

mybase=$1
shift

for var in "$@"
do
	cd $mybase
	cd $var
	./configure
	make
	make install
done

