#!/bin/bash
# Asher Bond 2011

apt-get update && apt-get -y upgrade
apt-get install git

# default dir
DIR='/var/lib'

cd $DIR
git clone git://github.com/AsherBond/MondocosmOS.git MondocosmOS
cd MondocosmOS
$DIR/install-it-all

cd $DIR
git clone git://github.com/AsherBond/MondocosmOS-Images.git
cd MondocosmOS-Images
$DIR/install-it-all
