#!/bin/bash
# Asher Bond 2011

# get code for mondoslam

# default directory
DIR='/var/lib'
cd $DIR

sudo apt-get update && apt-get -y upgrade
sudo apt-get -y install subversion cvs

# Ptamm dependencies
export CVS_RSH=ssh

cd $DIR
cvs -z3 -d:pserver:anonymous@cvs.savannah.nongnu.org:/sources/toon co TooN
cd TooN
./configure
make
make install

cd $DIR
cvs -z3 -d:pserver:anonymous@cvs.savannah.nongnu.org:/sources/libcvd co libcvd
cd libcvd
./configure
make
make install

cd $DIR
cvs -z3 -d:pserver:anonymous@cvs.savannah.nongnu.org:/sources/libcvd co gvars3
cd gvars3
./configure
make
make install

cd $DIR
svn co https://mplapack.svn.sourceforge.net/svnroot/mplapack mplapack
cd mlapack
./configure
make
make install

