// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKMake_DataMapOfHAsciiStringOfStepBuilder.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _TCollection_HAsciiString_HeaderFile
#include <TCollection_HAsciiString.hxx>
#endif
#ifndef _WOKMake_StepBuilder_HeaderFile
#include <WOKMake_StepBuilder.hxx>
#endif
#ifndef _WOKTools_HAsciiStringHasher_HeaderFile
#include <WOKTools_HAsciiStringHasher.hxx>
#endif
#ifndef _WOKMake_DataMapIteratorOfDataMapOfHAsciiStringOfStepBuilder_HeaderFile
#include <WOKMake_DataMapIteratorOfDataMapOfHAsciiStringOfStepBuilder.hxx>
#endif
 

#define TheKey Handle_TCollection_HAsciiString
#define TheKey_hxx <TCollection_HAsciiString.hxx>
#define TheItem WOKMake_StepBuilder
#define TheItem_hxx <WOKMake_StepBuilder.hxx>
#define Hasher WOKTools_HAsciiStringHasher
#define Hasher_hxx <WOKTools_HAsciiStringHasher.hxx>
#define WOKTools_DataMapIterator WOKMake_DataMapIteratorOfDataMapOfHAsciiStringOfStepBuilder
#define WOKTools_DataMapIterator_hxx <WOKMake_DataMapIteratorOfDataMapOfHAsciiStringOfStepBuilder.hxx>
#define WOKTools_DataMap WOKMake_DataMapOfHAsciiStringOfStepBuilder
#define WOKTools_DataMap_hxx <WOKMake_DataMapOfHAsciiStringOfStepBuilder.hxx>
#include <WOKTools_DataMap.gxx>

