// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKMake_DataMapOfHAsciiStringOfDevUnit.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _TCollection_HAsciiString_HeaderFile
#include <TCollection_HAsciiString.hxx>
#endif
#ifndef _WOKernel_DevUnit_HeaderFile
#include <WOKernel_DevUnit.hxx>
#endif
#ifndef _WOKTools_HAsciiStringHasher_HeaderFile
#include <WOKTools_HAsciiStringHasher.hxx>
#endif
#ifndef _WOKMake_DataMapIteratorOfDataMapOfHAsciiStringOfDevUnit_HeaderFile
#include <WOKMake_DataMapIteratorOfDataMapOfHAsciiStringOfDevUnit.hxx>
#endif
 

#define TheKey Handle_TCollection_HAsciiString
#define TheKey_hxx <TCollection_HAsciiString.hxx>
#define TheItem Handle_WOKernel_DevUnit
#define TheItem_hxx <WOKernel_DevUnit.hxx>
#define Hasher WOKTools_HAsciiStringHasher
#define Hasher_hxx <WOKTools_HAsciiStringHasher.hxx>
#define WOKTools_DataMapIterator WOKMake_DataMapIteratorOfDataMapOfHAsciiStringOfDevUnit
#define WOKTools_DataMapIterator_hxx <WOKMake_DataMapIteratorOfDataMapOfHAsciiStringOfDevUnit.hxx>
#define WOKTools_DataMap WOKMake_DataMapOfHAsciiStringOfDevUnit
#define WOKTools_DataMap_hxx <WOKMake_DataMapOfHAsciiStringOfDevUnit.hxx>
#include <WOKTools_DataMap.gxx>

