// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_HSequenceOfEngine.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_Engine_HeaderFile
#include <MS_Engine.hxx>
#endif
#ifndef _MS_SequenceOfEngine_HeaderFile
#include <MS_SequenceOfEngine.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(MS_HSequenceOfEngine)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MS_HSequenceOfEngine)


IMPLEMENT_DOWNCAST(MS_HSequenceOfEngine,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MS_HSequenceOfEngine)


#define Item Handle_MS_Engine
#define Item_hxx <MS_Engine.hxx>
#define TheSequence MS_SequenceOfEngine
#define TheSequence_hxx <MS_SequenceOfEngine.hxx>
#define TCollection_HSequence MS_HSequenceOfEngine
#define TCollection_HSequence_hxx <MS_HSequenceOfEngine.hxx>
#define Handle_TCollection_HSequence Handle_MS_HSequenceOfEngine
#define TCollection_HSequence_Type_() MS_HSequenceOfEngine_Type_()
#include <TCollection_HSequence.gxx>

