// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_HSequenceOfExecutable.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_Executable_HeaderFile
#include <MS_Executable.hxx>
#endif
#ifndef _MS_SequenceOfExecutable_HeaderFile
#include <MS_SequenceOfExecutable.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(MS_HSequenceOfExecutable)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MS_HSequenceOfExecutable)


IMPLEMENT_DOWNCAST(MS_HSequenceOfExecutable,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MS_HSequenceOfExecutable)


#define Item Handle_MS_Executable
#define Item_hxx <MS_Executable.hxx>
#define TheSequence MS_SequenceOfExecutable
#define TheSequence_hxx <MS_SequenceOfExecutable.hxx>
#define TCollection_HSequence MS_HSequenceOfExecutable
#define TCollection_HSequence_hxx <MS_HSequenceOfExecutable.hxx>
#define Handle_TCollection_HSequence Handle_MS_HSequenceOfExecutable
#define TCollection_HSequence_Type_() MS_HSequenceOfExecutable_Type_()
#include <TCollection_HSequence.gxx>

