// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_HSequenceOfExecFile.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_ExecFile_HeaderFile
#include <MS_ExecFile.hxx>
#endif
#ifndef _MS_SequenceOfExecFile_HeaderFile
#include <MS_SequenceOfExecFile.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(MS_HSequenceOfExecFile)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MS_HSequenceOfExecFile)


IMPLEMENT_DOWNCAST(MS_HSequenceOfExecFile,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MS_HSequenceOfExecFile)


#define Item Handle_MS_ExecFile
#define Item_hxx <MS_ExecFile.hxx>
#define TheSequence MS_SequenceOfExecFile
#define TheSequence_hxx <MS_SequenceOfExecFile.hxx>
#define TCollection_HSequence MS_HSequenceOfExecFile
#define TCollection_HSequence_hxx <MS_HSequenceOfExecFile.hxx>
#define Handle_TCollection_HSequence Handle_MS_HSequenceOfExecFile
#define TCollection_HSequence_Type_() MS_HSequenceOfExecFile_Type_()
#include <TCollection_HSequence.gxx>

