// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_HSequenceOfMethod.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_Method_HeaderFile
#include <MS_Method.hxx>
#endif
#ifndef _MS_SequenceOfMethod_HeaderFile
#include <MS_SequenceOfMethod.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(MS_HSequenceOfMethod)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MS_HSequenceOfMethod)


IMPLEMENT_DOWNCAST(MS_HSequenceOfMethod,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MS_HSequenceOfMethod)


#define Item Handle_MS_Method
#define Item_hxx <MS_Method.hxx>
#define TheSequence MS_SequenceOfMethod
#define TheSequence_hxx <MS_SequenceOfMethod.hxx>
#define TCollection_HSequence MS_HSequenceOfMethod
#define TCollection_HSequence_hxx <MS_HSequenceOfMethod.hxx>
#define Handle_TCollection_HSequence Handle_MS_HSequenceOfMethod
#define TCollection_HSequence_Type_() MS_HSequenceOfMethod_Type_()
#include <TCollection_HSequence.gxx>

