// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_HSequenceOfInstClass.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_InstClass_HeaderFile
#include <MS_InstClass.hxx>
#endif
#ifndef _MS_SequenceOfInstClass_HeaderFile
#include <MS_SequenceOfInstClass.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(MS_HSequenceOfInstClass)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MS_HSequenceOfInstClass)


IMPLEMENT_DOWNCAST(MS_HSequenceOfInstClass,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MS_HSequenceOfInstClass)


#define Item Handle_MS_InstClass
#define Item_hxx <MS_InstClass.hxx>
#define TheSequence MS_SequenceOfInstClass
#define TheSequence_hxx <MS_SequenceOfInstClass.hxx>
#define TCollection_HSequence MS_HSequenceOfInstClass
#define TCollection_HSequence_hxx <MS_HSequenceOfInstClass.hxx>
#define Handle_TCollection_HSequence Handle_MS_HSequenceOfInstClass
#define TCollection_HSequence_Type_() MS_HSequenceOfInstClass_Type_()
#include <TCollection_HSequence.gxx>

