// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_HSequenceOfMemberMet.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_MemberMet_HeaderFile
#include <MS_MemberMet.hxx>
#endif
#ifndef _MS_SequenceOfMemberMet_HeaderFile
#include <MS_SequenceOfMemberMet.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(MS_HSequenceOfMemberMet)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MS_HSequenceOfMemberMet)


IMPLEMENT_DOWNCAST(MS_HSequenceOfMemberMet,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MS_HSequenceOfMemberMet)


#define Item Handle_MS_MemberMet
#define Item_hxx <MS_MemberMet.hxx>
#define TheSequence MS_SequenceOfMemberMet
#define TheSequence_hxx <MS_SequenceOfMemberMet.hxx>
#define TCollection_HSequence MS_HSequenceOfMemberMet
#define TCollection_HSequence_hxx <MS_HSequenceOfMemberMet.hxx>
#define Handle_TCollection_HSequence Handle_MS_HSequenceOfMemberMet
#define TCollection_HSequence_Type_() MS_HSequenceOfMemberMet_Type_()
#include <TCollection_HSequence.gxx>

