// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_SequenceNodeOfSequenceOfGenClass.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _MS_GenClass_HeaderFile
#include <MS_GenClass.hxx>
#endif
#ifndef _MS_SequenceOfGenClass_HeaderFile
#include <MS_SequenceOfGenClass.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(MS_SequenceNodeOfSequenceOfGenClass)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MS_SequenceNodeOfSequenceOfGenClass)


IMPLEMENT_DOWNCAST(MS_SequenceNodeOfSequenceOfGenClass,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MS_SequenceNodeOfSequenceOfGenClass)


#define SeqItem Handle_MS_GenClass
#define SeqItem_hxx <MS_GenClass.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfGenClass
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfGenClass.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfGenClass
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfGenClass_Type_()
#define TCollection_Sequence MS_SequenceOfGenClass
#define TCollection_Sequence_hxx <MS_SequenceOfGenClass.hxx>
#include <TCollection_SequenceNode.gxx>

