// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_SequenceOfField.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_Field_HeaderFile
#include <MS_Field.hxx>
#endif
#ifndef _MS_SequenceNodeOfSequenceOfField_HeaderFile
#include <MS_SequenceNodeOfSequenceOfField.hxx>
#endif
 

#define SeqItem Handle_MS_Field
#define SeqItem_hxx <MS_Field.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfField
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfField.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfField
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfField_Type_()
#define TCollection_Sequence MS_SequenceOfField
#define TCollection_Sequence_hxx <MS_SequenceOfField.hxx>
#include <TCollection_Sequence.gxx>

