// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_SequenceOfPackage.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_Package_HeaderFile
#include <MS_Package.hxx>
#endif
#ifndef _MS_SequenceNodeOfSequenceOfPackage_HeaderFile
#include <MS_SequenceNodeOfSequenceOfPackage.hxx>
#endif
 

#define SeqItem Handle_MS_Package
#define SeqItem_hxx <MS_Package.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfPackage
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfPackage.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfPackage
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfPackage_Type_()
#define TCollection_Sequence MS_SequenceOfPackage
#define TCollection_Sequence_hxx <MS_SequenceOfPackage.hxx>
#include <TCollection_Sequence.gxx>

