// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_SequenceOfGenType.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_GenType_HeaderFile
#include <MS_GenType.hxx>
#endif
#ifndef _MS_SequenceNodeOfSequenceOfGenType_HeaderFile
#include <MS_SequenceNodeOfSequenceOfGenType.hxx>
#endif
 

#define SeqItem Handle_MS_GenType
#define SeqItem_hxx <MS_GenType.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfGenType
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfGenType.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfGenType
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfGenType_Type_()
#define TCollection_Sequence MS_SequenceOfGenType
#define TCollection_Sequence_hxx <MS_SequenceOfGenType.hxx>
#include <TCollection_Sequence.gxx>

