// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_SequenceOfSchema.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_Schema_HeaderFile
#include <MS_Schema.hxx>
#endif
#ifndef _MS_SequenceNodeOfSequenceOfSchema_HeaderFile
#include <MS_SequenceNodeOfSequenceOfSchema.hxx>
#endif
 

#define SeqItem Handle_MS_Schema
#define SeqItem_hxx <MS_Schema.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfSchema
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfSchema.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfSchema
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfSchema_Type_()
#define TCollection_Sequence MS_SequenceOfSchema
#define TCollection_Sequence_hxx <MS_SequenceOfSchema.hxx>
#include <TCollection_Sequence.gxx>

