// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MS_SequenceOfGlobalEntity.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _MS_GlobalEntity_HeaderFile
#include <MS_GlobalEntity.hxx>
#endif
#ifndef _MS_SequenceNodeOfSequenceOfGlobalEntity_HeaderFile
#include <MS_SequenceNodeOfSequenceOfGlobalEntity.hxx>
#endif
 

#define SeqItem Handle_MS_GlobalEntity
#define SeqItem_hxx <MS_GlobalEntity.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfGlobalEntity
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfGlobalEntity.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfGlobalEntity
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfGlobalEntity_Type_()
#define TCollection_Sequence MS_SequenceOfGlobalEntity
#define TCollection_Sequence_hxx <MS_SequenceOfGlobalEntity.hxx>
#include <TCollection_Sequence.gxx>

