// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKUtils_HSequenceOfPath.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _WOKUtils_Path_HeaderFile
#include <WOKUtils_Path.hxx>
#endif
#ifndef _WOKUtils_SequenceOfPath_HeaderFile
#include <WOKUtils_SequenceOfPath.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(WOKUtils_HSequenceOfPath)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WOKUtils_HSequenceOfPath)


IMPLEMENT_DOWNCAST(WOKUtils_HSequenceOfPath,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WOKUtils_HSequenceOfPath)


#define Item Handle_WOKUtils_Path
#define Item_hxx <WOKUtils_Path.hxx>
#define TheSequence WOKUtils_SequenceOfPath
#define TheSequence_hxx <WOKUtils_SequenceOfPath.hxx>
#define TCollection_HSequence WOKUtils_HSequenceOfPath
#define TCollection_HSequence_hxx <WOKUtils_HSequenceOfPath.hxx>
#define Handle_TCollection_HSequence Handle_WOKUtils_HSequenceOfPath
#define TCollection_HSequence_Type_() WOKUtils_HSequenceOfPath_Type_()
#include <TCollection_HSequence.gxx>

