// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKUtils_SequenceOfParamItem.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _WOKUtils_ParamItem_HeaderFile
#include <WOKUtils_ParamItem.hxx>
#endif
#ifndef _WOKUtils_SequenceNodeOfSequenceOfParamItem_HeaderFile
#include <WOKUtils_SequenceNodeOfSequenceOfParamItem.hxx>
#endif
 

#define SeqItem WOKUtils_ParamItem
#define SeqItem_hxx <WOKUtils_ParamItem.hxx>
#define TCollection_SequenceNode WOKUtils_SequenceNodeOfSequenceOfParamItem
#define TCollection_SequenceNode_hxx <WOKUtils_SequenceNodeOfSequenceOfParamItem.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKUtils_SequenceNodeOfSequenceOfParamItem
#define TCollection_SequenceNode_Type_() WOKUtils_SequenceNodeOfSequenceOfParamItem_Type_()
#define TCollection_Sequence WOKUtils_SequenceOfParamItem
#define TCollection_Sequence_hxx <WOKUtils_SequenceOfParamItem.hxx>
#include <TCollection_Sequence.gxx>

