// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKAPI_SequenceNodeOfSequenceOfMakeOption.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _WOKAPI_MakeOption_HeaderFile
#include <WOKAPI_MakeOption.hxx>
#endif
#ifndef _WOKAPI_SequenceOfMakeOption_HeaderFile
#include <WOKAPI_SequenceOfMakeOption.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(WOKAPI_SequenceNodeOfSequenceOfMakeOption)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WOKAPI_SequenceNodeOfSequenceOfMakeOption)


IMPLEMENT_DOWNCAST(WOKAPI_SequenceNodeOfSequenceOfMakeOption,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WOKAPI_SequenceNodeOfSequenceOfMakeOption)


#define SeqItem WOKAPI_MakeOption
#define SeqItem_hxx <WOKAPI_MakeOption.hxx>
#define TCollection_SequenceNode WOKAPI_SequenceNodeOfSequenceOfMakeOption
#define TCollection_SequenceNode_hxx <WOKAPI_SequenceNodeOfSequenceOfMakeOption.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKAPI_SequenceNodeOfSequenceOfMakeOption
#define TCollection_SequenceNode_Type_() WOKAPI_SequenceNodeOfSequenceOfMakeOption_Type_()
#define TCollection_Sequence WOKAPI_SequenceOfMakeOption
#define TCollection_Sequence_hxx <WOKAPI_SequenceOfMakeOption.hxx>
#include <TCollection_SequenceNode.gxx>

