// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKUnix_StackNodeOfStackOfDir.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _WOKUnix_StackOfDir_HeaderFile
#include <WOKUnix_StackOfDir.hxx>
#endif
#ifndef _WOKUnix_StackIteratorOfStackOfDir_HeaderFile
#include <WOKUnix_StackIteratorOfStackOfDir.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(WOKUnix_StackNodeOfStackOfDir)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WOKUnix_StackNodeOfStackOfDir)


IMPLEMENT_DOWNCAST(WOKUnix_StackNodeOfStackOfDir,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WOKUnix_StackNodeOfStackOfDir)


#define Item WOKUnix_Dir
#define Item_hxx <WOKUnix_Dir.hxx>
#define TCollection_StackNode WOKUnix_StackNodeOfStackOfDir
#define TCollection_StackNode_hxx <WOKUnix_StackNodeOfStackOfDir.hxx>
#define TCollection_StackIterator WOKUnix_StackIteratorOfStackOfDir
#define TCollection_StackIterator_hxx <WOKUnix_StackIteratorOfStackOfDir.hxx>
#define Handle_TCollection_StackNode Handle_WOKUnix_StackNodeOfStackOfDir
#define TCollection_StackNode_Type_() WOKUnix_StackNodeOfStackOfDir_Type_()
#define TCollection_Stack WOKUnix_StackOfDir
#define TCollection_Stack_hxx <WOKUnix_StackOfDir.hxx>
#include <TCollection_StackNode.gxx>

