// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <EDL_DataMapNodeOfMapOfTemplate.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TCollection_AsciiString_HeaderFile
#include <TCollection_AsciiString.hxx>
#endif
#ifndef _EDL_Template_HeaderFile
#include <EDL_Template.hxx>
#endif
#ifndef _EDL_MapOfTemplate_HeaderFile
#include <EDL_MapOfTemplate.hxx>
#endif
#ifndef _EDL_DataMapIteratorOfMapOfTemplate_HeaderFile
#include <EDL_DataMapIteratorOfMapOfTemplate.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(EDL_DataMapNodeOfMapOfTemplate)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(EDL_DataMapNodeOfMapOfTemplate)


IMPLEMENT_DOWNCAST(EDL_DataMapNodeOfMapOfTemplate,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(EDL_DataMapNodeOfMapOfTemplate)


#define TheKey TCollection_AsciiString
#define TheKey_hxx <TCollection_AsciiString.hxx>
#define TheItem EDL_Template
#define TheItem_hxx <EDL_Template.hxx>
#define Hasher TCollection_AsciiString
#define Hasher_hxx <TCollection_AsciiString.hxx>
#define TCollection_DataMapNode EDL_DataMapNodeOfMapOfTemplate
#define TCollection_DataMapNode_hxx <EDL_DataMapNodeOfMapOfTemplate.hxx>
#define TCollection_DataMapIterator EDL_DataMapIteratorOfMapOfTemplate
#define TCollection_DataMapIterator_hxx <EDL_DataMapIteratorOfMapOfTemplate.hxx>
#define Handle_TCollection_DataMapNode Handle_EDL_DataMapNodeOfMapOfTemplate
#define TCollection_DataMapNode_Type_() EDL_DataMapNodeOfMapOfTemplate_Type_()
#define TCollection_DataMap EDL_MapOfTemplate
#define TCollection_DataMap_hxx <EDL_MapOfTemplate.hxx>
#include <TCollection_DataMapNode.gxx>

