// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <EDL_DataMapNodeOfMapOfVariable.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TCollection_AsciiString_HeaderFile
#include <TCollection_AsciiString.hxx>
#endif
#ifndef _EDL_Variable_HeaderFile
#include <EDL_Variable.hxx>
#endif
#ifndef _EDL_MapOfVariable_HeaderFile
#include <EDL_MapOfVariable.hxx>
#endif
#ifndef _EDL_DataMapIteratorOfMapOfVariable_HeaderFile
#include <EDL_DataMapIteratorOfMapOfVariable.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(EDL_DataMapNodeOfMapOfVariable)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(EDL_DataMapNodeOfMapOfVariable)


IMPLEMENT_DOWNCAST(EDL_DataMapNodeOfMapOfVariable,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(EDL_DataMapNodeOfMapOfVariable)


#define TheKey TCollection_AsciiString
#define TheKey_hxx <TCollection_AsciiString.hxx>
#define TheItem EDL_Variable
#define TheItem_hxx <EDL_Variable.hxx>
#define Hasher TCollection_AsciiString
#define Hasher_hxx <TCollection_AsciiString.hxx>
#define TCollection_DataMapNode EDL_DataMapNodeOfMapOfVariable
#define TCollection_DataMapNode_hxx <EDL_DataMapNodeOfMapOfVariable.hxx>
#define TCollection_DataMapIterator EDL_DataMapIteratorOfMapOfVariable
#define TCollection_DataMapIterator_hxx <EDL_DataMapIteratorOfMapOfVariable.hxx>
#define Handle_TCollection_DataMapNode Handle_EDL_DataMapNodeOfMapOfVariable
#define TCollection_DataMapNode_Type_() EDL_DataMapNodeOfMapOfVariable_Type_()
#define TCollection_DataMap EDL_MapOfVariable
#define TCollection_DataMap_hxx <EDL_MapOfVariable.hxx>
#include <TCollection_DataMapNode.gxx>

