/*
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.audiomanager.client.voicechat;

import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;

/**
 *
 * @author nsimpson
 * @author Ronny Standtke <ronny.standtke@fhnw.ch>
 */
public class AddPhoneUserPanel extends javax.swing.JPanel {

    public AddPhoneUserPanel() {
        initComponents();
        addUserDetailsPanel.add(new PrivacyPanel(), BorderLayout.CENTER);
        validate();
    }

    public void showPrivacyPanel(boolean showPrivacy) {
        addUserDetailsPanel.setVisible(showPrivacy);
    }

    public String getPhoneName() {
        return nameTextField.getText();
    }

    public String getPhoneNumber() {
        return phoneTextField.getText();
    }

    public void setStatusMessage(String message) {
        statusLabel.setText(message);
    }

    public void addNameTextActionListener(ActionListener listener) {
        nameTextField.addActionListener(listener);
    }

    public void removeNameTextActionListener(ActionListener listener) {
        nameTextField.removeActionListener(listener);
    }

    public void addPhoneTextActionListener(ActionListener listener) {
        phoneTextField.addActionListener(listener);
    }

    public void removePhoneTextActionListener(ActionListener listener) {
        phoneTextField.removeActionListener(listener);
    }

    public void addNameTextKeyReleasedListener(KeyAdapter listener) {
        nameTextField.addKeyListener(listener);
    }

    public void removeNameTextKeyReleasedListener(KeyAdapter listener) {
        nameTextField.addKeyListener(listener);
    }

    public void addPhoneTextKeyReleasedListener(KeyAdapter listener) {
        phoneTextField.addKeyListener(listener);
    }

    public void removePhoneTextKeyReleasedListener(KeyAdapter listener) {
        phoneTextField.addKeyListener(listener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phonePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        addUserDetailsPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(0, 95));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(295, 95));

        phonePanel.setMinimumSize(new java.awt.Dimension(100, 91));
        phonePanel.setName("phonePanel"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jdesktop/wonderland/modules/audiomanager/client/resources/Bundle"); // NOI18N
        nameLabel.setText(bundle.getString("AddPhoneUserPanel.nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        nameTextField.setName("nameTextField"); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });

        phoneLabel.setText(bundle.getString("AddPhoneUserPanel.phoneLabel.text")); // NOI18N
        phoneLabel.setName("phoneLabel"); // NOI18N

        phoneTextField.setName("phoneTextField"); // NOI18N
        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });
        phoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneTextFieldKeyReleased(evt);
            }
        });

        statusLabel.setName("statusLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout phonePanelLayout = new org.jdesktop.layout.GroupLayout(phonePanel);
        phonePanel.setLayout(phonePanelLayout);
        phonePanelLayout.setHorizontalGroup(
            phonePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(phonePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(phonePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(nameLabel)
                    .add(phoneLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(phonePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(statusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 211, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(phonePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(phoneTextField)
                        .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        phonePanelLayout.setVerticalGroup(
            phonePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(phonePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(phonePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameLabel)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(phonePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(phoneTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(phoneLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE))
        );

        addUserDetailsPanel.setBackground(new java.awt.Color(0, 0, 0));
        addUserDetailsPanel.setName("addUserDetailsPanel"); // NOI18N
        addUserDetailsPanel.setLayout(new java.awt.BorderLayout());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(phonePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(addUserDetailsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(phonePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(0, 0, 0)
                .add(addUserDetailsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 2, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nameTextFieldActionPerformed

private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_phoneTextFieldActionPerformed

private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_nameTextFieldKeyReleased

private void phoneTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextFieldKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_phoneTextFieldKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addUserDetailsPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel phonePanel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
