// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKernel_SortedImpldepFromIterator.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _WOKernel_UnitGraph_HeaderFile
#include <WOKernel_UnitGraph.hxx>
#endif
#ifndef _TCollection_HAsciiString_HeaderFile
#include <TCollection_HAsciiString.hxx>
#endif
#ifndef _WOKernel_HAsciiStringHasher_HeaderFile
#include <WOKernel_HAsciiStringHasher.hxx>
#endif
#ifndef _WOKernel_ImplDepIterator_HeaderFile
#include <WOKernel_ImplDepIterator.hxx>
#endif
#ifndef _WOKernel_SCMapOfSortedImpldepFromIterator_HeaderFile
#include <WOKernel_SCMapOfSortedImpldepFromIterator.hxx>
#endif
#ifndef _WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator_HeaderFile
#include <WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator.hxx>
#endif
 

#define Graph Handle_WOKernel_UnitGraph
#define Graph_hxx <WOKernel_UnitGraph.hxx>
#define Vertex Handle_TCollection_HAsciiString
#define Vertex_hxx <TCollection_HAsciiString.hxx>
#define VHasher WOKernel_HAsciiStringHasher
#define VHasher_hxx <WOKernel_HAsciiStringHasher.hxx>
#define VIterator WOKernel_ImplDepIterator
#define VIterator_hxx <WOKernel_ImplDepIterator.hxx>
#define GraphTools_SCMap WOKernel_SCMapOfSortedImpldepFromIterator
#define GraphTools_SCMap_hxx <WOKernel_SCMapOfSortedImpldepFromIterator.hxx>
#define GraphTools_IndexedDataMapNodeOfSCMap WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator
#define GraphTools_IndexedDataMapNodeOfSCMap_hxx <WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator.hxx>
#define GraphTools_IndexedDataMapNodeOfSCMap WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator
#define GraphTools_IndexedDataMapNodeOfSCMap_hxx <WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator.hxx>
#define Handle_GraphTools_IndexedDataMapNodeOfSCMap Handle_WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator
#define GraphTools_IndexedDataMapNodeOfSCMap_Type_() WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator_Type_()
#define Handle_GraphTools_IndexedDataMapNodeOfSCMap Handle_WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator
#define GraphTools_IndexedDataMapNodeOfSCMap_Type_() WOKernel_IndexedDataMapNodeOfSCMapOfSortedImpldepFromIterator_Type_()
#define GraphTools_SortedStrgCmptsFromIterator WOKernel_SortedImpldepFromIterator
#define GraphTools_SortedStrgCmptsFromIterator_hxx <WOKernel_SortedImpldepFromIterator.hxx>
#include <GraphTools_SortedStrgCmptsFromIterator.gxx>

