// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKernel_SequenceOfFile.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _WOKernel_File_HeaderFile
#include <WOKernel_File.hxx>
#endif
#ifndef _WOKernel_SequenceNodeOfSequenceOfFile_HeaderFile
#include <WOKernel_SequenceNodeOfSequenceOfFile.hxx>
#endif
 

#define SeqItem Handle_WOKernel_File
#define SeqItem_hxx <WOKernel_File.hxx>
#define TCollection_SequenceNode WOKernel_SequenceNodeOfSequenceOfFile
#define TCollection_SequenceNode_hxx <WOKernel_SequenceNodeOfSequenceOfFile.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKernel_SequenceNodeOfSequenceOfFile
#define TCollection_SequenceNode_Type_() WOKernel_SequenceNodeOfSequenceOfFile_Type_()
#define TCollection_Sequence WOKernel_SequenceOfFile
#define TCollection_Sequence_hxx <WOKernel_SequenceOfFile.hxx>
#include <TCollection_Sequence.gxx>

