// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKernel_SequenceNodeOfSequenceOfSession.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _WOKernel_Session_HeaderFile
#include <WOKernel_Session.hxx>
#endif
#ifndef _WOKernel_SequenceOfSession_HeaderFile
#include <WOKernel_SequenceOfSession.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(WOKernel_SequenceNodeOfSequenceOfSession)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WOKernel_SequenceNodeOfSequenceOfSession)


IMPLEMENT_DOWNCAST(WOKernel_SequenceNodeOfSequenceOfSession,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WOKernel_SequenceNodeOfSequenceOfSession)


#define SeqItem Handle_WOKernel_Session
#define SeqItem_hxx <WOKernel_Session.hxx>
#define TCollection_SequenceNode WOKernel_SequenceNodeOfSequenceOfSession
#define TCollection_SequenceNode_hxx <WOKernel_SequenceNodeOfSequenceOfSession.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKernel_SequenceNodeOfSequenceOfSession
#define TCollection_SequenceNode_Type_() WOKernel_SequenceNodeOfSequenceOfSession_Type_()
#define TCollection_Sequence WOKernel_SequenceOfSession
#define TCollection_Sequence_hxx <WOKernel_SequenceOfSession.hxx>
#include <TCollection_SequenceNode.gxx>

