// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKernel_HSequenceOfFile.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _WOKernel_File_HeaderFile
#include <WOKernel_File.hxx>
#endif
#ifndef _WOKernel_SequenceOfFile_HeaderFile
#include <WOKernel_SequenceOfFile.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(WOKernel_HSequenceOfFile)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WOKernel_HSequenceOfFile)


IMPLEMENT_DOWNCAST(WOKernel_HSequenceOfFile,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WOKernel_HSequenceOfFile)


#define Item Handle_WOKernel_File
#define Item_hxx <WOKernel_File.hxx>
#define TheSequence WOKernel_SequenceOfFile
#define TheSequence_hxx <WOKernel_SequenceOfFile.hxx>
#define TCollection_HSequence WOKernel_HSequenceOfFile
#define TCollection_HSequence_hxx <WOKernel_HSequenceOfFile.hxx>
#define Handle_TCollection_HSequence Handle_WOKernel_HSequenceOfFile
#define TCollection_HSequence_Type_() WOKernel_HSequenceOfFile_Type_()
#include <TCollection_HSequence.gxx>

