// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _CPPJini_ClientInfo_HeaderFile
#define _CPPJini_ClientInfo_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_CPPJini_ClientInfo_HeaderFile
#include <Handle_CPPJini_ClientInfo.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _WOKTools_MapOfHAsciiString_HeaderFile
#include <WOKTools_MapOfHAsciiString.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Standard_Transient_HeaderFile
#include <Standard_Transient.hxx>
#endif
#ifndef _Handle_MS_MetaSchema_HeaderFile
#include <Handle_MS_MetaSchema.hxx>
#endif
#ifndef _CPPJini_ExtractionType_HeaderFile
#include <CPPJini_ExtractionType.hxx>
#endif
class TCollection_HAsciiString;
class MS_MetaSchema;


//! stores information about client and its types <br>
class CPPJini_ClientInfo : public Standard_Transient {

public:

  //! constructor <br>
  Standard_EXPORT   CPPJini_ClientInfo(const Handle(MS_MetaSchema)& aMS,const Handle(TCollection_HAsciiString)& aName,const Standard_Integer aLevel);
  //! checks if client has complete type <br>
  Standard_EXPORT     Standard_Boolean HasComplete(const Handle(TCollection_HAsciiString)& aName) const;
  //! checks if client has incomplete type <br>
  Standard_EXPORT     Standard_Boolean HasIncomplete(const Handle(TCollection_HAsciiString)& aName) const;
  //! checks if client has semicomplete type <br>
  Standard_EXPORT     Standard_Boolean HasSemicomplete(const Handle(TCollection_HAsciiString)& aName) const;
  //! checks if client has type defined or not <br>
  Standard_EXPORT     Standard_Boolean Defined(const Handle(TCollection_HAsciiString)& aName,CPPJini_ExtractionType& aType) const;
  //! returns <myName> field <br>
  Standard_EXPORT    const Handle_TCollection_HAsciiString& Name() const;
  //! returns level of the client in the 'uses' hierarchy <br>
        Standard_Integer Level() const;
  //! returns a flag indicating whether client is a <br>
//!          root in the 'uses' hierarchy <br>
        Standard_Boolean Root() const;
  //! sets client state indicating that the client is a root <br>
//!          in the 'uses' hierarchy <br>
        void SetRoot(const Standard_Boolean aRoot) ;
  //! sets a level of the client in the 'uses' hierarchy <br>
        void SetLevel(const Standard_Integer aLevel) ;




  DEFINE_STANDARD_RTTI(CPPJini_ClientInfo)

protected:




private: 


Handle_TCollection_HAsciiString myName;
WOKTools_MapOfHAsciiString myComplete;
WOKTools_MapOfHAsciiString myIncomplete;
WOKTools_MapOfHAsciiString mySemicomplete;
Standard_Integer myLevel;
Standard_Boolean myRoot;


};


#include <CPPJini_ClientInfo.lxx>



// other Inline functions and methods (like "C++: function call" methods)


#endif
