// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _EDL_Error_HeaderFile
#define _EDL_Error_HeaderFile


enum EDL_Error {
EDL_NORMAL,
EDL_SYNTAXERROR,
EDL_VARNOTFOUND,
EDL_TEMPMULTIPLEDEFINED,
EDL_TEMPLATENOTDEFINED,
EDL_LIBRARYNOTFOUND,
EDL_LIBNOTOPEN,
EDL_FUNCTIONNOTFOUND,
EDL_FILEOPENED,
EDL_FILENOTOPENED,
EDL_FILENOTFOUND,
EDL_TOOMANYINCLUDELEVEL
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
