// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _EDL_StackNodeOfStackOfBoolean_HeaderFile
#define _EDL_StackNodeOfStackOfBoolean_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_EDL_StackNodeOfStackOfBoolean_HeaderFile
#include <Handle_EDL_StackNodeOfStackOfBoolean.hxx>
#endif

#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class EDL_StackOfBoolean;
class EDL_StackIteratorOfStackOfBoolean;



class EDL_StackNodeOfStackOfBoolean : public TCollection_MapNode {

public:

  
      EDL_StackNodeOfStackOfBoolean(const Standard_Boolean& I,const TCollection_MapNodePtr& n);
  
        Standard_Boolean& Value() const;




  DEFINE_STANDARD_RTTI(EDL_StackNodeOfStackOfBoolean)

protected:




private: 


Standard_Boolean myValue;


};

#define Item Standard_Boolean
#define Item_hxx <Standard_Boolean.hxx>
#define TCollection_StackNode EDL_StackNodeOfStackOfBoolean
#define TCollection_StackNode_hxx <EDL_StackNodeOfStackOfBoolean.hxx>
#define TCollection_StackIterator EDL_StackIteratorOfStackOfBoolean
#define TCollection_StackIterator_hxx <EDL_StackIteratorOfStackOfBoolean.hxx>
#define Handle_TCollection_StackNode Handle_EDL_StackNodeOfStackOfBoolean
#define TCollection_StackNode_Type_() EDL_StackNodeOfStackOfBoolean_Type_()
#define TCollection_Stack EDL_StackOfBoolean
#define TCollection_Stack_hxx <EDL_StackOfBoolean.hxx>

#include <TCollection_StackNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_StackNode
#undef TCollection_StackNode_hxx
#undef TCollection_StackIterator
#undef TCollection_StackIterator_hxx
#undef Handle_TCollection_StackNode
#undef TCollection_StackNode_Type_
#undef TCollection_Stack
#undef TCollection_Stack_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
