// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _EDL_DataMapNodeOfMapOfTemplate_HeaderFile
#define _EDL_DataMapNodeOfMapOfTemplate_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_EDL_DataMapNodeOfMapOfTemplate_HeaderFile
#include <Handle_EDL_DataMapNodeOfMapOfTemplate.hxx>
#endif

#ifndef _TCollection_AsciiString_HeaderFile
#include <TCollection_AsciiString.hxx>
#endif
#ifndef _EDL_Template_HeaderFile
#include <EDL_Template.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class TCollection_AsciiString;
class EDL_Template;
class EDL_MapOfTemplate;
class EDL_DataMapIteratorOfMapOfTemplate;



class EDL_DataMapNodeOfMapOfTemplate : public TCollection_MapNode {

public:

  
      EDL_DataMapNodeOfMapOfTemplate(const TCollection_AsciiString& K,const EDL_Template& I,const TCollection_MapNodePtr& n);
  
        TCollection_AsciiString& Key() const;
  
        EDL_Template& Value() const;




  DEFINE_STANDARD_RTTI(EDL_DataMapNodeOfMapOfTemplate)

protected:




private: 


TCollection_AsciiString myKey;
EDL_Template myValue;


};

#define TheKey TCollection_AsciiString
#define TheKey_hxx <TCollection_AsciiString.hxx>
#define TheItem EDL_Template
#define TheItem_hxx <EDL_Template.hxx>
#define Hasher TCollection_AsciiString
#define Hasher_hxx <TCollection_AsciiString.hxx>
#define TCollection_DataMapNode EDL_DataMapNodeOfMapOfTemplate
#define TCollection_DataMapNode_hxx <EDL_DataMapNodeOfMapOfTemplate.hxx>
#define TCollection_DataMapIterator EDL_DataMapIteratorOfMapOfTemplate
#define TCollection_DataMapIterator_hxx <EDL_DataMapIteratorOfMapOfTemplate.hxx>
#define Handle_TCollection_DataMapNode Handle_EDL_DataMapNodeOfMapOfTemplate
#define TCollection_DataMapNode_Type_() EDL_DataMapNodeOfMapOfTemplate_Type_()
#define TCollection_DataMap EDL_MapOfTemplate
#define TCollection_DataMap_hxx <EDL_MapOfTemplate.hxx>

#include <TCollection_DataMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef TheItem
#undef TheItem_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_DataMapNode
#undef TCollection_DataMapNode_hxx
#undef TCollection_DataMapIterator
#undef TCollection_DataMapIterator_hxx
#undef Handle_TCollection_DataMapNode
#undef TCollection_DataMapNode_Type_
#undef TCollection_DataMap
#undef TCollection_DataMap_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
