// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_MS_Method_HeaderFile
#define _Handle_MS_Method_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_MS_Common_HeaderFile
#include <Handle_MS_Common.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(MS_Common);
class MS_Method;

DEFINE_STANDARD_HANDLE(MS_Method,MS_Common)

#endif
