// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_WOKBuilder_MSTemplateExtractor_HeaderFile
#define _Handle_WOKBuilder_MSTemplateExtractor_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_WOKBuilder_MSExtractor_HeaderFile
#include <Handle_WOKBuilder_MSExtractor.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(WOKBuilder_MSExtractor);
class WOKBuilder_MSTemplateExtractor;

DEFINE_STANDARD_HANDLE(WOKBuilder_MSTemplateExtractor,WOKBuilder_MSExtractor)

#endif
