// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_WOKStep_TransitiveLinkList_HeaderFile
#define _Handle_WOKStep_TransitiveLinkList_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_WOKStep_ComputeLinkList_HeaderFile
#include <Handle_WOKStep_ComputeLinkList.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(WOKStep_ComputeLinkList);
class WOKStep_TransitiveLinkList;

DEFINE_STANDARD_HANDLE(WOKStep_TransitiveLinkList,WOKStep_ComputeLinkList)

#endif
