// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_WOKTools_EnvValue_HeaderFile
#define _Handle_WOKTools_EnvValue_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_WOKTools_ReturnValue_HeaderFile
#include <Handle_WOKTools_ReturnValue.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(WOKTools_ReturnValue);
class WOKTools_EnvValue;

DEFINE_STANDARD_HANDLE(WOKTools_EnvValue,WOKTools_ReturnValue)

#endif
