// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_MS_Construc_HeaderFile
#define _Handle_MS_Construc_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_MS_MemberMet_HeaderFile
#include <Handle_MS_MemberMet.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(MS_MemberMet);
class MS_Construc;

DEFINE_STANDARD_HANDLE(MS_Construc,MS_MemberMet)

#endif
