// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_WOKStep_MSFill_HeaderFile
#define _Handle_WOKStep_MSFill_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_WOKStep_MSStep_HeaderFile
#include <Handle_WOKStep_MSStep.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(WOKStep_MSStep);
class WOKStep_MSFill;

DEFINE_STANDARD_HANDLE(WOKStep_MSFill,WOKStep_MSStep)

#endif
