// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_WOKUnix_MixedOutput_HeaderFile
#define _Handle_WOKUnix_MixedOutput_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_WOKUnix_ProcessOutput_HeaderFile
#include <Handle_WOKUnix_ProcessOutput.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(WOKUnix_ProcessOutput);
class WOKUnix_MixedOutput;

DEFINE_STANDARD_HANDLE(WOKUnix_MixedOutput,WOKUnix_ProcessOutput)

#endif
