// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_Alias_HeaderFile
#define _MS_Alias_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_Alias_HeaderFile
#include <Handle_MS_Alias.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _MS_NatType_HeaderFile
#include <MS_NatType.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class TCollection_HAsciiString;



class MS_Alias : public MS_NatType {

public:

  
  Standard_EXPORT   MS_Alias(const Handle(TCollection_HAsciiString)& aName,const Handle(TCollection_HAsciiString)& aPackage,const Handle(TCollection_HAsciiString)& aContainer,const Standard_Boolean aPrivate);
  
  Standard_EXPORT     void Type(const Handle(TCollection_HAsciiString)& aType,const Handle(TCollection_HAsciiString)& aPackage) ;
  
  Standard_EXPORT    const Handle_TCollection_HAsciiString& Type() const;
  //! returns the real type of the alias (used if the alias type is already an alias). <br>
  Standard_EXPORT     Handle_TCollection_HAsciiString DeepType() const;




  DEFINE_STANDARD_RTTI(MS_Alias)

protected:




private: 


Handle_TCollection_HAsciiString myType;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
