// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_ExecFile_HeaderFile
#define _MS_ExecFile_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_ExecFile_HeaderFile
#include <Handle_MS_ExecFile.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _MS_Language_HeaderFile
#include <MS_Language.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
class TCollection_HAsciiString;



class MS_ExecFile : public MMgt_TShared {

public:

  
  Standard_EXPORT   MS_ExecFile(const Handle(TCollection_HAsciiString)& aName);
  
  Standard_EXPORT     void SetName(const Handle(TCollection_HAsciiString)& aName) ;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Name() const;
  
  Standard_EXPORT     void SetLanguage(const MS_Language aLang) ;
  
  Standard_EXPORT     MS_Language Language() const;




  DEFINE_STANDARD_RTTI(MS_ExecFile)

protected:




private: 


Handle_TCollection_HAsciiString myName;
MS_Language myLanguage;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
