// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_Executable_HeaderFile
#define _MS_Executable_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_Executable_HeaderFile
#include <Handle_MS_Executable.hxx>
#endif

#ifndef _Handle_MS_HSequenceOfExecPart_HeaderFile
#include <Handle_MS_HSequenceOfExecPart.hxx>
#endif
#ifndef _MS_Exec_HeaderFile
#include <MS_Exec.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
class MS_HSequenceOfExecPart;
class TCollection_HAsciiString;



class MS_Executable : public MS_Exec {

public:

  
  Standard_EXPORT   MS_Executable(const Handle(TCollection_HAsciiString)& anExecutable);
  
  Standard_EXPORT     void AddParts(const Handle(MS_HSequenceOfExecPart)& theParts) ;
  
  Standard_EXPORT     Handle_MS_HSequenceOfExecPart Parts() const;




  DEFINE_STANDARD_RTTI(MS_Executable)

protected:




private: 


Handle_MS_HSequenceOfExecPart myParts;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
