// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_ExternMet_HeaderFile
#define _MS_ExternMet_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_ExternMet_HeaderFile
#include <Handle_MS_ExternMet.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _MS_Method_HeaderFile
#include <MS_Method.hxx>
#endif
class TCollection_HAsciiString;



class MS_ExternMet : public MS_Method {

public:

  
  Standard_EXPORT   MS_ExternMet(const Handle(TCollection_HAsciiString)& aName);
  
  Standard_EXPORT   MS_ExternMet(const Handle(TCollection_HAsciiString)& aName,const Handle(TCollection_HAsciiString)& aPackage);
  
  Standard_EXPORT   virtual  void CreateFullName() ;
  
  Standard_EXPORT     void Package(const Handle(TCollection_HAsciiString)& aPack) ;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Package() const;
  
  Standard_EXPORT   virtual  void Raises(const Handle(TCollection_HAsciiString)& aExcept) ;
  
  Standard_EXPORT     void Raises(const Handle(TCollection_HAsciiString)& aExcept,const Handle(TCollection_HAsciiString)& aPackage) ;




  DEFINE_STANDARD_RTTI(MS_ExternMet)

protected:




private: 


Handle_TCollection_HAsciiString myPackage;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
