// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_GlobalEntity_HeaderFile
#define _MS_GlobalEntity_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_GlobalEntity_HeaderFile
#include <Handle_MS_GlobalEntity.hxx>
#endif

#ifndef _MS_Common_HeaderFile
#include <MS_Common.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
class TCollection_HAsciiString;



class MS_GlobalEntity : public MS_Common {

public:





  DEFINE_STANDARD_RTTI(MS_GlobalEntity)

protected:

  
  Standard_EXPORT   MS_GlobalEntity(const Handle(TCollection_HAsciiString)& aName);



private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
