// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_HArray1OfParam_HeaderFile
#define _MS_HArray1OfParam_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_HArray1OfParam_HeaderFile
#include <Handle_MS_HArray1OfParam.hxx>
#endif

#ifndef _MS_Array1OfParam_HeaderFile
#include <MS_Array1OfParam.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
#ifndef _Handle_MS_Param_HeaderFile
#include <Handle_MS_Param.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_RangeError;
class Standard_DimensionMismatch;
class Standard_OutOfRange;
class Standard_OutOfMemory;
class MS_Param;
class MS_Array1OfParam;



class MS_HArray1OfParam : public MMgt_TShared {

public:

  
  Standard_EXPORT   MS_HArray1OfParam(const Standard_Integer Low,const Standard_Integer Up);
  
  Standard_EXPORT   MS_HArray1OfParam(const Standard_Integer Low,const Standard_Integer Up,const Handle(MS_Param)& V);
  
  Standard_EXPORT     void Init(const Handle(MS_Param)& V) ;
  
        Standard_Integer Length() const;
  
        Standard_Integer Lower() const;
  
        Standard_Integer Upper() const;
  
        void SetValue(const Standard_Integer Index,const Handle(MS_Param)& Value) ;
  
       const Handle_MS_Param& Value(const Standard_Integer Index) const;
  
        Handle_MS_Param& ChangeValue(const Standard_Integer Index) ;
  
       const MS_Array1OfParam& Array1() const;
  
        MS_Array1OfParam& ChangeArray1() ;




  DEFINE_STANDARD_RTTI(MS_HArray1OfParam)

protected:




private: 


MS_Array1OfParam myArray;


};

#define ItemHArray1 Handle_MS_Param
#define ItemHArray1_hxx <MS_Param.hxx>
#define TheArray1 MS_Array1OfParam
#define TheArray1_hxx <MS_Array1OfParam.hxx>
#define TCollection_HArray1 MS_HArray1OfParam
#define TCollection_HArray1_hxx <MS_HArray1OfParam.hxx>
#define Handle_TCollection_HArray1 Handle_MS_HArray1OfParam
#define TCollection_HArray1_Type_() MS_HArray1OfParam_Type_()

#include <TCollection_HArray1.lxx>

#undef ItemHArray1
#undef ItemHArray1_hxx
#undef TheArray1
#undef TheArray1_hxx
#undef TCollection_HArray1
#undef TCollection_HArray1_hxx
#undef Handle_TCollection_HArray1
#undef TCollection_HArray1_Type_


// other Inline functions and methods (like "C++: function call" methods)


#endif
