// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_PrimType_HeaderFile
#define _MS_PrimType_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_PrimType_HeaderFile
#include <Handle_MS_PrimType.hxx>
#endif

#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
#ifndef _MS_NatType_HeaderFile
#include <MS_NatType.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class TColStd_HSequenceOfHAsciiString;
class TCollection_HAsciiString;



class MS_PrimType : public MS_NatType {

public:

  
  Standard_EXPORT   MS_PrimType(const Handle(TCollection_HAsciiString)& aName,const Handle(TCollection_HAsciiString)& aPackage,const Handle(TCollection_HAsciiString)& aContainer,const Standard_Boolean aPrivate);
  
  Standard_EXPORT     void Inherit(const Handle(TCollection_HAsciiString)& aClass,const Handle(TCollection_HAsciiString)& aPackage) ;
  
  Standard_EXPORT     Handle_TColStd_HSequenceOfHAsciiString GetInheritsNames() const;
  
  Standard_EXPORT     Handle_TColStd_HSequenceOfHAsciiString GetFullInheritsNames() const;
  
  Standard_EXPORT     Standard_Boolean IsPersistent() const;
  
  Standard_EXPORT     Standard_Boolean IsTransient() const;
  
  Standard_EXPORT     Standard_Boolean IsStorable() const;




  DEFINE_STANDARD_RTTI(MS_PrimType)

protected:




private: 


Handle_TColStd_HSequenceOfHAsciiString myInherits;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
