// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_SequenceOfEngine_HeaderFile
#define _MS_SequenceOfEngine_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_MS_Engine_HeaderFile
#include <Handle_MS_Engine.hxx>
#endif
#ifndef _Handle_MS_SequenceNodeOfSequenceOfEngine_HeaderFile
#include <Handle_MS_SequenceNodeOfSequenceOfEngine.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class MS_Engine;
class MS_SequenceNodeOfSequenceOfEngine;



class MS_SequenceOfEngine  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      MS_SequenceOfEngine();
  
  Standard_EXPORT     void Clear() ;
~MS_SequenceOfEngine()
{
  Clear();
}
  
  Standard_EXPORT    const MS_SequenceOfEngine& Assign(const MS_SequenceOfEngine& Other) ;
   const MS_SequenceOfEngine& operator =(const MS_SequenceOfEngine& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const Handle(MS_Engine)& T) ;
  
        void Append(MS_SequenceOfEngine& S) ;
  
  Standard_EXPORT     void Prepend(const Handle(MS_Engine)& T) ;
  
        void Prepend(MS_SequenceOfEngine& S) ;
  
        void InsertBefore(const Standard_Integer Index,const Handle(MS_Engine)& T) ;
  
        void InsertBefore(const Standard_Integer Index,MS_SequenceOfEngine& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const Handle(MS_Engine)& T) ;
  
        void InsertAfter(const Standard_Integer Index,MS_SequenceOfEngine& S) ;
  
  Standard_EXPORT    const Handle_MS_Engine& First() const;
  
  Standard_EXPORT    const Handle_MS_Engine& Last() const;
  
        void Split(const Standard_Integer Index,MS_SequenceOfEngine& Sub) ;
  
  Standard_EXPORT    const Handle_MS_Engine& Value(const Standard_Integer Index) const;
   const Handle_MS_Engine& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const Handle(MS_Engine)& I) ;
  
  Standard_EXPORT     Handle_MS_Engine& ChangeValue(const Standard_Integer Index) ;
    Handle_MS_Engine& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   MS_SequenceOfEngine(const MS_SequenceOfEngine& Other);




};

#define SeqItem Handle_MS_Engine
#define SeqItem_hxx <MS_Engine.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfEngine
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfEngine.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfEngine
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfEngine_Type_()
#define TCollection_Sequence MS_SequenceOfEngine
#define TCollection_Sequence_hxx <MS_SequenceOfEngine.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
