// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_SequenceOfType_HeaderFile
#define _MS_SequenceOfType_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_MS_Type_HeaderFile
#include <Handle_MS_Type.hxx>
#endif
#ifndef _Handle_MS_SequenceNodeOfSequenceOfType_HeaderFile
#include <Handle_MS_SequenceNodeOfSequenceOfType.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class MS_Type;
class MS_SequenceNodeOfSequenceOfType;



class MS_SequenceOfType  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      MS_SequenceOfType();
  
  Standard_EXPORT     void Clear() ;
~MS_SequenceOfType()
{
  Clear();
}
  
  Standard_EXPORT    const MS_SequenceOfType& Assign(const MS_SequenceOfType& Other) ;
   const MS_SequenceOfType& operator =(const MS_SequenceOfType& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const Handle(MS_Type)& T) ;
  
        void Append(MS_SequenceOfType& S) ;
  
  Standard_EXPORT     void Prepend(const Handle(MS_Type)& T) ;
  
        void Prepend(MS_SequenceOfType& S) ;
  
        void InsertBefore(const Standard_Integer Index,const Handle(MS_Type)& T) ;
  
        void InsertBefore(const Standard_Integer Index,MS_SequenceOfType& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const Handle(MS_Type)& T) ;
  
        void InsertAfter(const Standard_Integer Index,MS_SequenceOfType& S) ;
  
  Standard_EXPORT    const Handle_MS_Type& First() const;
  
  Standard_EXPORT    const Handle_MS_Type& Last() const;
  
        void Split(const Standard_Integer Index,MS_SequenceOfType& Sub) ;
  
  Standard_EXPORT    const Handle_MS_Type& Value(const Standard_Integer Index) const;
   const Handle_MS_Type& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const Handle(MS_Type)& I) ;
  
  Standard_EXPORT     Handle_MS_Type& ChangeValue(const Standard_Integer Index) ;
    Handle_MS_Type& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   MS_SequenceOfType(const MS_SequenceOfType& Other);




};

#define SeqItem Handle_MS_Type
#define SeqItem_hxx <MS_Type.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfType
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfType.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfType
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfType_Type_()
#define TCollection_Sequence MS_SequenceOfType
#define TCollection_Sequence_hxx <MS_SequenceOfType.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
