// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_SequenceNodeOfSequenceOfExternMet_HeaderFile
#define _MS_SequenceNodeOfSequenceOfExternMet_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_SequenceNodeOfSequenceOfExternMet_HeaderFile
#include <Handle_MS_SequenceNodeOfSequenceOfExternMet.hxx>
#endif

#ifndef _Handle_MS_ExternMet_HeaderFile
#include <Handle_MS_ExternMet.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class MS_ExternMet;
class MS_SequenceOfExternMet;



class MS_SequenceNodeOfSequenceOfExternMet : public TCollection_SeqNode {

public:

  
      MS_SequenceNodeOfSequenceOfExternMet(const Handle(MS_ExternMet)& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Handle_MS_ExternMet& Value() const;




  DEFINE_STANDARD_RTTI(MS_SequenceNodeOfSequenceOfExternMet)

protected:




private: 


Handle_MS_ExternMet myValue;


};

#define SeqItem Handle_MS_ExternMet
#define SeqItem_hxx <MS_ExternMet.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfExternMet
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfExternMet.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfExternMet
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfExternMet_Type_()
#define TCollection_Sequence MS_SequenceOfExternMet
#define TCollection_Sequence_hxx <MS_SequenceOfExternMet.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
