// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_SequenceNodeOfSequenceOfEngine_HeaderFile
#define _MS_SequenceNodeOfSequenceOfEngine_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_SequenceNodeOfSequenceOfEngine_HeaderFile
#include <Handle_MS_SequenceNodeOfSequenceOfEngine.hxx>
#endif

#ifndef _Handle_MS_Engine_HeaderFile
#include <Handle_MS_Engine.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class MS_Engine;
class MS_SequenceOfEngine;



class MS_SequenceNodeOfSequenceOfEngine : public TCollection_SeqNode {

public:

  
      MS_SequenceNodeOfSequenceOfEngine(const Handle(MS_Engine)& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Handle_MS_Engine& Value() const;




  DEFINE_STANDARD_RTTI(MS_SequenceNodeOfSequenceOfEngine)

protected:




private: 


Handle_MS_Engine myValue;


};

#define SeqItem Handle_MS_Engine
#define SeqItem_hxx <MS_Engine.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfEngine
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfEngine.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfEngine
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfEngine_Type_()
#define TCollection_Sequence MS_SequenceOfEngine
#define TCollection_Sequence_hxx <MS_SequenceOfEngine.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
