// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_SequenceNodeOfSequenceOfParam_HeaderFile
#define _MS_SequenceNodeOfSequenceOfParam_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_SequenceNodeOfSequenceOfParam_HeaderFile
#include <Handle_MS_SequenceNodeOfSequenceOfParam.hxx>
#endif

#ifndef _Handle_MS_Param_HeaderFile
#include <Handle_MS_Param.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class MS_Param;
class MS_SequenceOfParam;



class MS_SequenceNodeOfSequenceOfParam : public TCollection_SeqNode {

public:

  
      MS_SequenceNodeOfSequenceOfParam(const Handle(MS_Param)& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Handle_MS_Param& Value() const;




  DEFINE_STANDARD_RTTI(MS_SequenceNodeOfSequenceOfParam)

protected:




private: 


Handle_MS_Param myValue;


};

#define SeqItem Handle_MS_Param
#define SeqItem_hxx <MS_Param.hxx>
#define TCollection_SequenceNode MS_SequenceNodeOfSequenceOfParam
#define TCollection_SequenceNode_hxx <MS_SequenceNodeOfSequenceOfParam.hxx>
#define Handle_TCollection_SequenceNode Handle_MS_SequenceNodeOfSequenceOfParam
#define TCollection_SequenceNode_Type_() MS_SequenceNodeOfSequenceOfParam_Type_()
#define TCollection_Sequence MS_SequenceOfParam
#define TCollection_Sequence_hxx <MS_SequenceOfParam.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
