// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MS_Type_HeaderFile
#define _MS_Type_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_MS_Type_HeaderFile
#include <Handle_MS_Type.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _MS_Common_HeaderFile
#include <MS_Common.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_MS_Package_HeaderFile
#include <Handle_MS_Package.hxx>
#endif
class TCollection_HAsciiString;
class MS_Package;



class MS_Type : public MS_Common {

public:

  
  Standard_EXPORT   virtual  Standard_Boolean Private() const = 0;
  
  Standard_EXPORT   virtual  void Package(const Handle(TCollection_HAsciiString)& aPackage) ;
  
  Standard_EXPORT   virtual  Handle_MS_Package Package() const;




  DEFINE_STANDARD_RTTI(MS_Type)

protected:

  
  Standard_EXPORT   MS_Type(const Handle(TCollection_HAsciiString)& aName);
  
  Standard_EXPORT   MS_Type(const Handle(TCollection_HAsciiString)& aName,const Handle(TCollection_HAsciiString)& aPackage,const Handle(TCollection_HAsciiString)& Container,const Standard_Boolean InPackage);



private: 


Handle_TCollection_HAsciiString myPackage;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
