// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKAPI_SequenceNodeOfSequenceOfMakeOption_HeaderFile
#define _WOKAPI_SequenceNodeOfSequenceOfMakeOption_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKAPI_SequenceNodeOfSequenceOfMakeOption_HeaderFile
#include <Handle_WOKAPI_SequenceNodeOfSequenceOfMakeOption.hxx>
#endif

#ifndef _WOKAPI_MakeOption_HeaderFile
#include <WOKAPI_MakeOption.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class WOKAPI_MakeOption;
class WOKAPI_SequenceOfMakeOption;



class WOKAPI_SequenceNodeOfSequenceOfMakeOption : public TCollection_SeqNode {

public:

  
      WOKAPI_SequenceNodeOfSequenceOfMakeOption(const WOKAPI_MakeOption& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        WOKAPI_MakeOption& Value() const;




  DEFINE_STANDARD_RTTI(WOKAPI_SequenceNodeOfSequenceOfMakeOption)

protected:




private: 


WOKAPI_MakeOption myValue;


};

#define SeqItem WOKAPI_MakeOption
#define SeqItem_hxx <WOKAPI_MakeOption.hxx>
#define TCollection_SequenceNode WOKAPI_SequenceNodeOfSequenceOfMakeOption
#define TCollection_SequenceNode_hxx <WOKAPI_SequenceNodeOfSequenceOfMakeOption.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKAPI_SequenceNodeOfSequenceOfMakeOption
#define TCollection_SequenceNode_Type_() WOKAPI_SequenceNodeOfSequenceOfMakeOption_Type_()
#define TCollection_Sequence WOKAPI_SequenceOfMakeOption
#define TCollection_Sequence_hxx <WOKAPI_SequenceOfMakeOption.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
