// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKAPI_SequenceOfFile_HeaderFile
#define _WOKAPI_SequenceOfFile_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_WOKAPI_SequenceNodeOfSequenceOfFile_HeaderFile
#include <Handle_WOKAPI_SequenceNodeOfSequenceOfFile.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class WOKAPI_File;
class WOKAPI_SequenceNodeOfSequenceOfFile;



class WOKAPI_SequenceOfFile  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      WOKAPI_SequenceOfFile();
  
  Standard_EXPORT     void Clear() ;
~WOKAPI_SequenceOfFile()
{
  Clear();
}
  
  Standard_EXPORT    const WOKAPI_SequenceOfFile& Assign(const WOKAPI_SequenceOfFile& Other) ;
   const WOKAPI_SequenceOfFile& operator =(const WOKAPI_SequenceOfFile& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const WOKAPI_File& T) ;
  
        void Append(WOKAPI_SequenceOfFile& S) ;
  
  Standard_EXPORT     void Prepend(const WOKAPI_File& T) ;
  
        void Prepend(WOKAPI_SequenceOfFile& S) ;
  
        void InsertBefore(const Standard_Integer Index,const WOKAPI_File& T) ;
  
        void InsertBefore(const Standard_Integer Index,WOKAPI_SequenceOfFile& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const WOKAPI_File& T) ;
  
        void InsertAfter(const Standard_Integer Index,WOKAPI_SequenceOfFile& S) ;
  
  Standard_EXPORT    const WOKAPI_File& First() const;
  
  Standard_EXPORT    const WOKAPI_File& Last() const;
  
        void Split(const Standard_Integer Index,WOKAPI_SequenceOfFile& Sub) ;
  
  Standard_EXPORT    const WOKAPI_File& Value(const Standard_Integer Index) const;
   const WOKAPI_File& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const WOKAPI_File& I) ;
  
  Standard_EXPORT     WOKAPI_File& ChangeValue(const Standard_Integer Index) ;
    WOKAPI_File& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   WOKAPI_SequenceOfFile(const WOKAPI_SequenceOfFile& Other);




};

#define SeqItem WOKAPI_File
#define SeqItem_hxx <WOKAPI_File.hxx>
#define TCollection_SequenceNode WOKAPI_SequenceNodeOfSequenceOfFile
#define TCollection_SequenceNode_hxx <WOKAPI_SequenceNodeOfSequenceOfFile.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKAPI_SequenceNodeOfSequenceOfFile
#define TCollection_SequenceNode_Type_() WOKAPI_SequenceNodeOfSequenceOfFile_Type_()
#define TCollection_Sequence WOKAPI_SequenceOfFile
#define TCollection_Sequence_hxx <WOKAPI_SequenceOfFile.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
