// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKAPI_Locator_HeaderFile
#define _WOKAPI_Locator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Handle_WOKernel_Locator_HeaderFile
#include <Handle_WOKernel_Locator.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
class WOKernel_Locator;
class WOKAPI_Workbench;
class WOKAPI_Session;
class TColStd_HSequenceOfHAsciiString;
class WOKAPI_File;
class TCollection_HAsciiString;
class WOKAPI_Entity;
class WOKAPI_Unit;



class WOKAPI_Locator  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   WOKAPI_Locator();
  
  Standard_EXPORT   WOKAPI_Locator(const Handle(WOKernel_Locator)& alocator);
  
  Standard_EXPORT     Standard_Boolean IsValid() const;
  
  Standard_EXPORT     void Set(const Handle(WOKernel_Locator)& alocator) ;
  
  Standard_EXPORT     void Set(const WOKAPI_Workbench& awb) ;
  
  Standard_EXPORT     void Set(const WOKAPI_Session& asession,const Handle(TColStd_HSequenceOfHAsciiString)& avisibility) ;
  
  Standard_EXPORT     void Reset() const;
  
  Standard_EXPORT     void Check() const;
  
  Standard_EXPORT     Handle_WOKernel_Locator Locator() const;
  
  Standard_EXPORT     WOKAPI_File Locate(const Handle(TCollection_HAsciiString)& alocatorname) const;
  
  Standard_EXPORT     WOKAPI_File Locate(const WOKAPI_Entity& anent,const Handle(TCollection_HAsciiString)& atype,const Handle(TCollection_HAsciiString)& aname) const;
  
  Standard_EXPORT     WOKAPI_File Locate(const WOKAPI_Entity& anent,const Handle(TCollection_HAsciiString)& atype) const;
  
  Standard_EXPORT     void Locate(WOKAPI_File& afile) const;
  
  Standard_EXPORT     WOKAPI_Unit LocateUnit(const Handle(TCollection_HAsciiString)& alocatorname) const;





protected:





private:



Handle_WOKernel_Locator mylocator;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
