// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKAPI_File_HeaderFile
#define _WOKAPI_File_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Handle_WOKernel_File_HeaderFile
#include <Handle_WOKernel_File.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
class WOKernel_File;
class WOKAPI_Unit;
class WOKAPI_Session;
class WOKAPI_Entity;
class WOKAPI_Locator;
class TCollection_HAsciiString;



class WOKAPI_File  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   WOKAPI_File();
  
  Standard_EXPORT     WOKAPI_Entity NestingEntity() const;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Type() const;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Name() const;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString LocatorName() const;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString UserPath() const;
  
  Standard_EXPORT     Standard_Boolean Exists() const;
  
  Standard_EXPORT     Standard_Boolean IsLocalTo(const WOKAPI_Entity& aent) const;
  
  Standard_EXPORT     Standard_Boolean IsFile() const;
  
  Standard_EXPORT     Standard_Boolean IsDirectory() const;
  
  Standard_EXPORT     Standard_Boolean IsValid() const;
  
  Standard_EXPORT     Standard_Boolean IsLocated() const;
  
  Standard_EXPORT     Standard_Boolean IsDBMSDependent() const;
  
  Standard_EXPORT     Standard_Boolean IsStationDependent() const;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Path() const;
  
  Standard_EXPORT     void Locate(const WOKAPI_Locator& alocator) ;
  
  Standard_EXPORT     void Located() ;
  
  Standard_EXPORT     void UnLocated() ;


friend class WOKAPI_Unit;
friend class WOKAPI_Session;
friend class WOKAPI_Entity;
friend class WOKAPI_Locator;



protected:





private:

  
  Standard_EXPORT     void Set(const Handle(WOKernel_File)& afile) ;


Handle_WOKernel_File myfile;
Standard_Boolean mylocated;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
