// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKAPI_SequenceNodeOfSequenceOfMakeStep_HeaderFile
#define _WOKAPI_SequenceNodeOfSequenceOfMakeStep_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKAPI_SequenceNodeOfSequenceOfMakeStep_HeaderFile
#include <Handle_WOKAPI_SequenceNodeOfSequenceOfMakeStep.hxx>
#endif

#ifndef _WOKAPI_MakeStep_HeaderFile
#include <WOKAPI_MakeStep.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class WOKAPI_MakeStep;
class WOKAPI_SequenceOfMakeStep;



class WOKAPI_SequenceNodeOfSequenceOfMakeStep : public TCollection_SeqNode {

public:

  
      WOKAPI_SequenceNodeOfSequenceOfMakeStep(const WOKAPI_MakeStep& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        WOKAPI_MakeStep& Value() const;




  DEFINE_STANDARD_RTTI(WOKAPI_SequenceNodeOfSequenceOfMakeStep)

protected:




private: 


WOKAPI_MakeStep myValue;


};

#define SeqItem WOKAPI_MakeStep
#define SeqItem_hxx <WOKAPI_MakeStep.hxx>
#define TCollection_SequenceNode WOKAPI_SequenceNodeOfSequenceOfMakeStep
#define TCollection_SequenceNode_hxx <WOKAPI_SequenceNodeOfSequenceOfMakeStep.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKAPI_SequenceNodeOfSequenceOfMakeStep
#define TCollection_SequenceNode_Type_() WOKAPI_SequenceNodeOfSequenceOfMakeStep_Type_()
#define TCollection_Sequence WOKAPI_SequenceOfMakeStep
#define TCollection_Sequence_hxx <WOKAPI_SequenceOfMakeStep.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
