// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKAPI_SequenceNodeOfSequenceOfFile_HeaderFile
#define _WOKAPI_SequenceNodeOfSequenceOfFile_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKAPI_SequenceNodeOfSequenceOfFile_HeaderFile
#include <Handle_WOKAPI_SequenceNodeOfSequenceOfFile.hxx>
#endif

#ifndef _WOKAPI_File_HeaderFile
#include <WOKAPI_File.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class WOKAPI_File;
class WOKAPI_SequenceOfFile;



class WOKAPI_SequenceNodeOfSequenceOfFile : public TCollection_SeqNode {

public:

  
      WOKAPI_SequenceNodeOfSequenceOfFile(const WOKAPI_File& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        WOKAPI_File& Value() const;




  DEFINE_STANDARD_RTTI(WOKAPI_SequenceNodeOfSequenceOfFile)

protected:




private: 


WOKAPI_File myValue;


};

#define SeqItem WOKAPI_File
#define SeqItem_hxx <WOKAPI_File.hxx>
#define TCollection_SequenceNode WOKAPI_SequenceNodeOfSequenceOfFile
#define TCollection_SequenceNode_hxx <WOKAPI_SequenceNodeOfSequenceOfFile.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKAPI_SequenceNodeOfSequenceOfFile
#define TCollection_SequenceNode_Type_() WOKAPI_SequenceNodeOfSequenceOfFile_Type_()
#define TCollection_Sequence WOKAPI_SequenceOfFile
#define TCollection_Sequence_hxx <WOKAPI_SequenceOfFile.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
