// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKBuilder_SequenceNodeOfSequenceOfExtension_HeaderFile
#define _WOKBuilder_SequenceNodeOfSequenceOfExtension_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKBuilder_SequenceNodeOfSequenceOfExtension_HeaderFile
#include <Handle_WOKBuilder_SequenceNodeOfSequenceOfExtension.hxx>
#endif

#ifndef _WOKUtils_Extension_HeaderFile
#include <WOKUtils_Extension.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class WOKBuilder_SequenceOfExtension;



class WOKBuilder_SequenceNodeOfSequenceOfExtension : public TCollection_SeqNode {

public:

  
      WOKBuilder_SequenceNodeOfSequenceOfExtension(const WOKUtils_Extension& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        WOKUtils_Extension& Value() const;




  DEFINE_STANDARD_RTTI(WOKBuilder_SequenceNodeOfSequenceOfExtension)

protected:




private: 


WOKUtils_Extension myValue;


};

#define SeqItem WOKUtils_Extension
#define SeqItem_hxx <WOKUtils_Extension.hxx>
#define TCollection_SequenceNode WOKBuilder_SequenceNodeOfSequenceOfExtension
#define TCollection_SequenceNode_hxx <WOKBuilder_SequenceNodeOfSequenceOfExtension.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKBuilder_SequenceNodeOfSequenceOfExtension
#define TCollection_SequenceNode_Type_() WOKBuilder_SequenceNodeOfSequenceOfExtension_Type_()
#define TCollection_Sequence WOKBuilder_SequenceOfExtension
#define TCollection_Sequence_hxx <WOKBuilder_SequenceOfExtension.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
