// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKBuilder_CodeGenerator_HeaderFile
#define _WOKBuilder_CodeGenerator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKBuilder_CodeGenerator_HeaderFile
#include <Handle_WOKBuilder_CodeGenerator.hxx>
#endif

#ifndef _Handle_WOKBuilder_CodeGenFile_HeaderFile
#include <Handle_WOKBuilder_CodeGenFile.hxx>
#endif
#ifndef _WOKBuilder_ToolInShell_HeaderFile
#include <WOKBuilder_ToolInShell.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _WOKBuilder_BuildStatus_HeaderFile
#include <WOKBuilder_BuildStatus.hxx>
#endif
class WOKBuilder_CodeGenFile;
class Standard_ProgramError;
class TCollection_HAsciiString;
class WOKUtils_Param;



class WOKBuilder_CodeGenerator : public WOKBuilder_ToolInShell {

public:

  
  Standard_EXPORT   WOKBuilder_CodeGenerator(const Handle(TCollection_HAsciiString)& aname,const WOKUtils_Param& params);
  
  Standard_EXPORT     void SetCodeGenFile(const Handle(WOKBuilder_CodeGenFile)& afile) ;
  
  Standard_EXPORT     Handle_WOKBuilder_CodeGenFile CodeGenFile() const;
  
  Standard_EXPORT     WOKBuilder_BuildStatus Execute() ;




  DEFINE_STANDARD_RTTI(WOKBuilder_CodeGenerator)

protected:




private: 


Handle_WOKBuilder_CodeGenFile myfile;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
