// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKBuilder_ToolInShell_HeaderFile
#define _WOKBuilder_ToolInShell_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKBuilder_ToolInShell_HeaderFile
#include <Handle_WOKBuilder_ToolInShell.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_WOKUtils_Shell_HeaderFile
#include <Handle_WOKUtils_Shell.hxx>
#endif
#ifndef _Handle_WOKBuilder_HSequenceOfExtension_HeaderFile
#include <Handle_WOKBuilder_HSequenceOfExtension.hxx>
#endif
#ifndef _WOKBuilder_Tool_HeaderFile
#include <WOKBuilder_Tool.hxx>
#endif
#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
#ifndef _Handle_WOKBuilder_HSequenceOfEntity_HeaderFile
#include <Handle_WOKBuilder_HSequenceOfEntity.hxx>
#endif
class TCollection_HAsciiString;
class WOKUtils_Shell;
class WOKBuilder_HSequenceOfExtension;
class WOKUtils_Param;
class TColStd_HSequenceOfHAsciiString;
class WOKBuilder_HSequenceOfEntity;



class WOKBuilder_ToolInShell : public WOKBuilder_Tool {

public:

  
  Standard_EXPORT     void SetShell(const Handle(WOKUtils_Shell)& ashell) ;
  
  Standard_EXPORT     void SetTemplate(const Handle(TCollection_HAsciiString)& aname) ;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Template() const;
  
  Standard_EXPORT     Handle_WOKBuilder_HSequenceOfExtension Extensions() const;
  
  Standard_EXPORT     void SetExtensions(const Handle(WOKBuilder_HSequenceOfExtension)& exts) ;
  
  Standard_EXPORT     Handle_TColStd_HSequenceOfHAsciiString TreatedExtensionNames() const;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString OptionLine() const;
  
  Standard_EXPORT   virtual  void Load() ;
  
  Standard_EXPORT     Handle_WOKBuilder_HSequenceOfEntity EvalProduction() const;




  DEFINE_STANDARD_RTTI(WOKBuilder_ToolInShell)

protected:

  
  Standard_EXPORT   WOKBuilder_ToolInShell(const Handle(TCollection_HAsciiString)& aname,const WOKUtils_Param& params);
  
  Standard_EXPORT     Handle_WOKUtils_Shell Shell() const;
  
  Standard_EXPORT     void ResetShell() const;



private: 


Handle_TCollection_HAsciiString myfile;
Handle_WOKUtils_Shell myshell;
Handle_TCollection_HAsciiString mytemplate;
Handle_WOKBuilder_HSequenceOfExtension myexts;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
