// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKBuilder_ArchiveExtract_HeaderFile
#define _WOKBuilder_ArchiveExtract_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKBuilder_ArchiveExtract_HeaderFile
#include <Handle_WOKBuilder_ArchiveExtract.hxx>
#endif

#ifndef _Handle_WOKBuilder_ArchiveLibrary_HeaderFile
#include <Handle_WOKBuilder_ArchiveLibrary.hxx>
#endif
#ifndef _WOKBuilder_ToolInShell_HeaderFile
#include <WOKBuilder_ToolInShell.hxx>
#endif
#ifndef _WOKBuilder_BuildStatus_HeaderFile
#include <WOKBuilder_BuildStatus.hxx>
#endif
class WOKBuilder_ArchiveLibrary;
class Standard_ProgramError;
class WOKUtils_Param;



class WOKBuilder_ArchiveExtract : public WOKBuilder_ToolInShell {

public:

  
  Standard_EXPORT   WOKBuilder_ArchiveExtract(const WOKUtils_Param& params);
  
  Standard_EXPORT   virtual  void Load() ;
  
  Standard_EXPORT     void SetArchive(const Handle(WOKBuilder_ArchiveLibrary)& anarchive) ;
  
  Standard_EXPORT     Handle_WOKBuilder_ArchiveLibrary Archive() const;
  
  Standard_EXPORT     WOKBuilder_BuildStatus Execute() ;




  DEFINE_STANDARD_RTTI(WOKBuilder_ArchiveExtract)

protected:




private: 


Handle_WOKBuilder_ArchiveLibrary mylib;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
