// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKBuilder_SequenceOfEntity_HeaderFile
#define _WOKBuilder_SequenceOfEntity_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_WOKBuilder_Entity_HeaderFile
#include <Handle_WOKBuilder_Entity.hxx>
#endif
#ifndef _Handle_WOKBuilder_SequenceNodeOfSequenceOfEntity_HeaderFile
#include <Handle_WOKBuilder_SequenceNodeOfSequenceOfEntity.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class WOKBuilder_Entity;
class WOKBuilder_SequenceNodeOfSequenceOfEntity;



class WOKBuilder_SequenceOfEntity  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      WOKBuilder_SequenceOfEntity();
  
  Standard_EXPORT     void Clear() ;
~WOKBuilder_SequenceOfEntity()
{
  Clear();
}
  
  Standard_EXPORT    const WOKBuilder_SequenceOfEntity& Assign(const WOKBuilder_SequenceOfEntity& Other) ;
   const WOKBuilder_SequenceOfEntity& operator =(const WOKBuilder_SequenceOfEntity& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const Handle(WOKBuilder_Entity)& T) ;
  
        void Append(WOKBuilder_SequenceOfEntity& S) ;
  
  Standard_EXPORT     void Prepend(const Handle(WOKBuilder_Entity)& T) ;
  
        void Prepend(WOKBuilder_SequenceOfEntity& S) ;
  
        void InsertBefore(const Standard_Integer Index,const Handle(WOKBuilder_Entity)& T) ;
  
        void InsertBefore(const Standard_Integer Index,WOKBuilder_SequenceOfEntity& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const Handle(WOKBuilder_Entity)& T) ;
  
        void InsertAfter(const Standard_Integer Index,WOKBuilder_SequenceOfEntity& S) ;
  
  Standard_EXPORT    const Handle_WOKBuilder_Entity& First() const;
  
  Standard_EXPORT    const Handle_WOKBuilder_Entity& Last() const;
  
        void Split(const Standard_Integer Index,WOKBuilder_SequenceOfEntity& Sub) ;
  
  Standard_EXPORT    const Handle_WOKBuilder_Entity& Value(const Standard_Integer Index) const;
   const Handle_WOKBuilder_Entity& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const Handle(WOKBuilder_Entity)& I) ;
  
  Standard_EXPORT     Handle_WOKBuilder_Entity& ChangeValue(const Standard_Integer Index) ;
    Handle_WOKBuilder_Entity& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   WOKBuilder_SequenceOfEntity(const WOKBuilder_SequenceOfEntity& Other);




};

#define SeqItem Handle_WOKBuilder_Entity
#define SeqItem_hxx <WOKBuilder_Entity.hxx>
#define TCollection_SequenceNode WOKBuilder_SequenceNodeOfSequenceOfEntity
#define TCollection_SequenceNode_hxx <WOKBuilder_SequenceNodeOfSequenceOfEntity.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKBuilder_SequenceNodeOfSequenceOfEntity
#define TCollection_SequenceNode_Type_() WOKBuilder_SequenceNodeOfSequenceOfEntity_Type_()
#define TCollection_Sequence WOKBuilder_SequenceOfEntity
#define TCollection_Sequence_hxx <WOKBuilder_SequenceOfEntity.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
