// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKBuilder_QueueNodeOfQueueOfMSAction_HeaderFile
#define _WOKBuilder_QueueNodeOfQueueOfMSAction_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKBuilder_QueueNodeOfQueueOfMSAction_HeaderFile
#include <Handle_WOKBuilder_QueueNodeOfQueueOfMSAction.hxx>
#endif

#ifndef _Handle_WOKBuilder_MSAction_HeaderFile
#include <Handle_WOKBuilder_MSAction.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class WOKBuilder_MSAction;
class WOKBuilder_QueueOfMSAction;



class WOKBuilder_QueueNodeOfQueueOfMSAction : public TCollection_MapNode {

public:

  
      WOKBuilder_QueueNodeOfQueueOfMSAction(const Handle(WOKBuilder_MSAction)& I,const TCollection_MapNodePtr& n);
  
        Handle_WOKBuilder_MSAction& Value() const;




  DEFINE_STANDARD_RTTI(WOKBuilder_QueueNodeOfQueueOfMSAction)

protected:




private: 


Handle_WOKBuilder_MSAction myValue;


};

#define Item Handle_WOKBuilder_MSAction
#define Item_hxx <WOKBuilder_MSAction.hxx>
#define TCollection_QueueNode WOKBuilder_QueueNodeOfQueueOfMSAction
#define TCollection_QueueNode_hxx <WOKBuilder_QueueNodeOfQueueOfMSAction.hxx>
#define Handle_TCollection_QueueNode Handle_WOKBuilder_QueueNodeOfQueueOfMSAction
#define TCollection_QueueNode_Type_() WOKBuilder_QueueNodeOfQueueOfMSAction_Type_()
#define TCollection_Queue WOKBuilder_QueueOfMSAction
#define TCollection_Queue_hxx <WOKBuilder_QueueOfMSAction.hxx>

#include <TCollection_QueueNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_QueueNode
#undef TCollection_QueueNode_hxx
#undef Handle_TCollection_QueueNode
#undef TCollection_QueueNode_Type_
#undef TCollection_Queue
#undef TCollection_Queue_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
