// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKBuilder_TarFile_HeaderFile
#define _WOKBuilder_TarFile_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKBuilder_TarFile_HeaderFile
#include <Handle_WOKBuilder_TarFile.hxx>
#endif

#ifndef _WOKBuilder_Miscellaneous_HeaderFile
#include <WOKBuilder_Miscellaneous.hxx>
#endif
#ifndef _Handle_WOKUtils_Path_HeaderFile
#include <Handle_WOKUtils_Path.hxx>
#endif
class WOKUtils_Path;



class WOKBuilder_TarFile : public WOKBuilder_Miscellaneous {

public:

  
  Standard_EXPORT   WOKBuilder_TarFile(const Handle(WOKUtils_Path)& apath);




  DEFINE_STANDARD_RTTI(WOKBuilder_TarFile)

protected:




private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
