// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKBuilder_EXELinker_HeaderFile
#define _WOKBuilder_EXELinker_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKBuilder_EXELinker_HeaderFile
#include <Handle_WOKBuilder_EXELinker.hxx>
#endif

#ifndef _WOKBuilder_WNTLinker_HeaderFile
#include <WOKBuilder_WNTLinker.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
class TCollection_HAsciiString;
class WOKUtils_Param;


//! provides tool to build an executable file <br>
class WOKBuilder_EXELinker : public WOKBuilder_WNTLinker {

public:

  //! create a class instance <br>
  Standard_EXPORT   WOKBuilder_EXELinker(const Handle(TCollection_HAsciiString)& aName,const WOKUtils_Param& aParams);
  //! evaluats tool command line <br>
  Standard_EXPORT     Handle_TCollection_HAsciiString EvalHeader() ;
  //! evaluates extension for name of the command file <br>
  Standard_EXPORT     Handle_TCollection_HAsciiString EvalCFExt() ;
  //! evaluates additional information for the tool <br>
  Standard_EXPORT     Handle_TCollection_HAsciiString EvalFooter() ;




  DEFINE_STANDARD_RTTI(WOKBuilder_EXELinker)

protected:




private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
