// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_UnitNesting_HeaderFile
#define _WOKernel_UnitNesting_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKernel_UnitNesting_HeaderFile
#include <Handle_WOKernel_UnitNesting.hxx>
#endif

#ifndef _WOKernel_UnitTypeBase_HeaderFile
#include <WOKernel_UnitTypeBase.hxx>
#endif
#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
#ifndef _WOKernel_Entity_HeaderFile
#include <WOKernel_Entity.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_WOKernel_Entity_HeaderFile
#include <Handle_WOKernel_Entity.hxx>
#endif
#ifndef _Handle_WOKernel_File_HeaderFile
#include <Handle_WOKernel_File.hxx>
#endif
#ifndef _Handle_WOKernel_DevUnit_HeaderFile
#include <Handle_WOKernel_DevUnit.hxx>
#endif
#ifndef _Standard_Character_HeaderFile
#include <Standard_Character.hxx>
#endif
class TColStd_HSequenceOfHAsciiString;
class Standard_ProgramError;
class TCollection_HAsciiString;
class WOKernel_Entity;
class WOKernel_File;
class WOKernel_DevUnit;
class WOKernel_UnitTypeBase;



class WOKernel_UnitNesting : public WOKernel_Entity {

public:

  
  Standard_EXPORT     void Open() ;
  
  Standard_EXPORT     void Close() ;
  
  Standard_EXPORT     Handle_TColStd_HSequenceOfHAsciiString Units() const;
  
  Standard_EXPORT     Handle_WOKernel_DevUnit GetDevUnit(const Standard_Character akey,const Handle(TCollection_HAsciiString)& aname) const;
  
  Standard_EXPORT     Handle_WOKernel_DevUnit GetDevUnit(const Handle(TCollection_HAsciiString)& atype,const Handle(TCollection_HAsciiString)& aname) const;
  
  Standard_EXPORT    const WOKernel_UnitTypeBase& KnownTypes() const;
  
  Standard_EXPORT     void AddUnit(const Handle(WOKernel_DevUnit)& aunit) ;
  
  Standard_EXPORT     void RemoveUnit(const Handle(WOKernel_DevUnit)& aunit) ;




  DEFINE_STANDARD_RTTI(WOKernel_UnitNesting)

protected:

  
  Standard_EXPORT   WOKernel_UnitNesting(const Handle(TCollection_HAsciiString)& aname,const Handle(WOKernel_Entity)& anesting);



private: 

  
  Standard_EXPORT   virtual  Handle_TColStd_HSequenceOfHAsciiString GetUnitList()  = 0;
  
  Standard_EXPORT   virtual  Handle_WOKernel_File GetUnitListFile() const = 0;
  
  Standard_EXPORT     void DumpUnitList() const;

WOKernel_UnitTypeBase mytypebase;
Handle_TColStd_HSequenceOfHAsciiString myunits;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
