// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_StationID_HeaderFile
#define _WOKernel_StationID_HeaderFile


enum WOKernel_StationID {
WOKernel_SUN,
WOKernel_DECOSF,
WOKernel_SGI,
WOKernel_HP,
WOKernel_WNT,
WOKernel_MAC,
WOKernel_LIN,
WOKernel_AIX,
WOKernel_BSD,
WOKernel_VMS,
WOKernel_UnknownStation
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
