// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_Warehouse_HeaderFile
#define _WOKernel_Warehouse_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKernel_Warehouse_HeaderFile
#include <Handle_WOKernel_Warehouse.hxx>
#endif

#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
#ifndef _WOKernel_Entity_HeaderFile
#include <WOKernel_Entity.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_WOKernel_Factory_HeaderFile
#include <Handle_WOKernel_Factory.hxx>
#endif
#ifndef _Handle_WOKernel_Parcel_HeaderFile
#include <Handle_WOKernel_Parcel.hxx>
#endif
class TColStd_HSequenceOfHAsciiString;
class TCollection_HAsciiString;
class WOKernel_Factory;
class WOKernel_Parcel;


//! Warehouse contains parcels used by the workshops <br>
//!          of the factory <br>
class WOKernel_Warehouse : public WOKernel_Entity {

public:

  
  Standard_EXPORT   WOKernel_Warehouse(const Handle(TCollection_HAsciiString)& aname,const Handle(WOKernel_Factory)& anesting);
  
  Standard_EXPORT   virtual  Handle_TCollection_HAsciiString EntityCode() const;
  
  Standard_EXPORT   virtual  void Open() ;
  
  Standard_EXPORT   virtual  void Close() ;
  
  Standard_EXPORT     void AddParcel(const Handle(WOKernel_Parcel)& aparcel) ;
  
  Standard_EXPORT     void RemoveParcel(const Handle(WOKernel_Parcel)& aparcel) ;
  
  Standard_EXPORT     Handle_TColStd_HSequenceOfHAsciiString Parcels() const;




  DEFINE_STANDARD_RTTI(WOKernel_Warehouse)

protected:




private: 

  
  Standard_EXPORT     void DumpParcelList() const;

Handle_TColStd_HSequenceOfHAsciiString myparcels;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
