// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_SequenceNodeOfSequenceOfSession_HeaderFile
#define _WOKernel_SequenceNodeOfSequenceOfSession_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKernel_SequenceNodeOfSequenceOfSession_HeaderFile
#include <Handle_WOKernel_SequenceNodeOfSequenceOfSession.hxx>
#endif

#ifndef _Handle_WOKernel_Session_HeaderFile
#include <Handle_WOKernel_Session.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class WOKernel_Session;
class WOKernel_SequenceOfSession;



class WOKernel_SequenceNodeOfSequenceOfSession : public TCollection_SeqNode {

public:

  
      WOKernel_SequenceNodeOfSequenceOfSession(const Handle(WOKernel_Session)& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Handle_WOKernel_Session& Value() const;




  DEFINE_STANDARD_RTTI(WOKernel_SequenceNodeOfSequenceOfSession)

protected:




private: 


Handle_WOKernel_Session myValue;


};

#define SeqItem Handle_WOKernel_Session
#define SeqItem_hxx <WOKernel_Session.hxx>
#define TCollection_SequenceNode WOKernel_SequenceNodeOfSequenceOfSession
#define TCollection_SequenceNode_hxx <WOKernel_SequenceNodeOfSequenceOfSession.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKernel_SequenceNodeOfSequenceOfSession
#define TCollection_SequenceNode_Type_() WOKernel_SequenceNodeOfSequenceOfSession_Type_()
#define TCollection_Sequence WOKernel_SequenceOfSession
#define TCollection_Sequence_hxx <WOKernel_SequenceOfSession.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
