// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_Locator_HeaderFile
#define _WOKernel_Locator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKernel_Locator_HeaderFile
#include <Handle_WOKernel_Locator.hxx>
#endif

#ifndef _Handle_WOKernel_Session_HeaderFile
#include <Handle_WOKernel_Session.hxx>
#endif
#ifndef _WOKernel_DataMapOfHAsciiStringOfFile_HeaderFile
#include <WOKernel_DataMapOfHAsciiStringOfFile.hxx>
#endif
#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
#ifndef _Handle_WOKernel_Workbench_HeaderFile
#include <Handle_WOKernel_Workbench.hxx>
#endif
#ifndef _Handle_WOKernel_File_HeaderFile
#include <Handle_WOKernel_File.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_WOKernel_DevUnit_HeaderFile
#include <Handle_WOKernel_DevUnit.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class WOKernel_Session;
class TColStd_HSequenceOfHAsciiString;
class WOKernel_Workbench;
class WOKernel_File;
class TCollection_HAsciiString;
class WOKernel_DevUnit;



class WOKernel_Locator : public MMgt_TShared {

public:

  
  Standard_EXPORT   WOKernel_Locator(const Handle(WOKernel_Workbench)& awb);
  
  Standard_EXPORT   WOKernel_Locator(const Handle(WOKernel_Session)& asession,const Handle(TColStd_HSequenceOfHAsciiString)& avisibility);
  
  Standard_EXPORT     Handle_WOKernel_Session Session() const;
  
  Standard_EXPORT     Handle_TColStd_HSequenceOfHAsciiString Visibility() const;
  
  Standard_EXPORT     void Reset() ;
  
  Standard_EXPORT     void Check() ;
  
  Standard_EXPORT    const Handle_WOKernel_File& Locate(const Handle(TCollection_HAsciiString)& alocatorname) ;
  
  Standard_EXPORT    const Handle_WOKernel_File& Locate(const Handle(TCollection_HAsciiString)& atype,const Handle(TCollection_HAsciiString)& aname) ;
  
  Standard_EXPORT    const Handle_WOKernel_File& Locate(const Handle(TCollection_HAsciiString)& aunitname,const Handle(TCollection_HAsciiString)& atype,const Handle(TCollection_HAsciiString)& aname) ;
  
  Standard_EXPORT     Handle_WOKernel_DevUnit LocateDevUnit(const Handle(TCollection_HAsciiString)& adevunitname) ;
  
  Standard_EXPORT     Standard_Boolean ChangeAdd(const Handle(WOKernel_File)& afile) ;
  
  Standard_EXPORT     Standard_Boolean ChangeRemove(const Handle(WOKernel_File)& afile) ;




  DEFINE_STANDARD_RTTI(WOKernel_Locator)

protected:




private: 

  
  Standard_EXPORT    const Handle_WOKernel_File& Locate(const Handle(TCollection_HAsciiString)& alocatorname,const Handle(TCollection_HAsciiString)& aunitname,const Handle(TCollection_HAsciiString)& atype,const Handle(TCollection_HAsciiString)& aname) ;

Handle_WOKernel_Session mysession;
WOKernel_DataMapOfHAsciiStringOfFile mymap;
Handle_TColStd_HSequenceOfHAsciiString myvisibility;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
