// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_EntityIterator_HeaderFile
#define _WOKernel_EntityIterator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfFactory_HeaderFile
#include <WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfFactory.hxx>
#endif
#ifndef _WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWarehouse_HeaderFile
#include <WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWarehouse.hxx>
#endif
#ifndef _WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWorkshop_HeaderFile
#include <WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWorkshop.hxx>
#endif
#ifndef _WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfParcel_HeaderFile
#include <WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfParcel.hxx>
#endif
#ifndef _WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWorkbench_HeaderFile
#include <WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWorkbench.hxx>
#endif
#ifndef _WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfDevUnit_HeaderFile
#include <WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfDevUnit.hxx>
#endif
#ifndef _Handle_WOKernel_Session_HeaderFile
#include <Handle_WOKernel_Session.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_WOKernel_Entity_HeaderFile
#include <Handle_WOKernel_Entity.hxx>
#endif
class WOKernel_Session;
class TCollection_HAsciiString;
class WOKernel_Entity;



class WOKernel_EntityIterator  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   WOKernel_EntityIterator(const Handle(WOKernel_Session)& asession);
  
  Standard_EXPORT     Standard_Boolean More() const;
  
  Standard_EXPORT    const Handle_TCollection_HAsciiString& Key() const;
  
  Standard_EXPORT    const Handle_WOKernel_Entity& Value() const;
  
  Standard_EXPORT     void Next() ;





protected:





private:



WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfFactory myfactit;
WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWarehouse mywareit;
WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWorkshop myshopit;
WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfParcel myparcit;
WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfWorkbench mybenchit;
WOKernel_DataMapIteratorOfDataMapOfHAsciiStringOfDevUnit myunitit;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
