// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_SequenceOfDBMSID_HeaderFile
#define _WOKernel_SequenceOfDBMSID_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _WOKernel_DBMSID_HeaderFile
#include <WOKernel_DBMSID.hxx>
#endif
#ifndef _Handle_WOKernel_SequenceNodeOfSequenceOfDBMSID_HeaderFile
#include <Handle_WOKernel_SequenceNodeOfSequenceOfDBMSID.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class WOKernel_SequenceNodeOfSequenceOfDBMSID;



class WOKernel_SequenceOfDBMSID  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      WOKernel_SequenceOfDBMSID();
  
  Standard_EXPORT     void Clear() ;
~WOKernel_SequenceOfDBMSID()
{
  Clear();
}
  
  Standard_EXPORT    const WOKernel_SequenceOfDBMSID& Assign(const WOKernel_SequenceOfDBMSID& Other) ;
   const WOKernel_SequenceOfDBMSID& operator =(const WOKernel_SequenceOfDBMSID& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const WOKernel_DBMSID& T) ;
  
        void Append(WOKernel_SequenceOfDBMSID& S) ;
  
  Standard_EXPORT     void Prepend(const WOKernel_DBMSID& T) ;
  
        void Prepend(WOKernel_SequenceOfDBMSID& S) ;
  
        void InsertBefore(const Standard_Integer Index,const WOKernel_DBMSID& T) ;
  
        void InsertBefore(const Standard_Integer Index,WOKernel_SequenceOfDBMSID& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const WOKernel_DBMSID& T) ;
  
        void InsertAfter(const Standard_Integer Index,WOKernel_SequenceOfDBMSID& S) ;
  
  Standard_EXPORT    const WOKernel_DBMSID& First() const;
  
  Standard_EXPORT    const WOKernel_DBMSID& Last() const;
  
        void Split(const Standard_Integer Index,WOKernel_SequenceOfDBMSID& Sub) ;
  
  Standard_EXPORT    const WOKernel_DBMSID& Value(const Standard_Integer Index) const;
   const WOKernel_DBMSID& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const WOKernel_DBMSID& I) ;
  
  Standard_EXPORT     WOKernel_DBMSID& ChangeValue(const Standard_Integer Index) ;
    WOKernel_DBMSID& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   WOKernel_SequenceOfDBMSID(const WOKernel_SequenceOfDBMSID& Other);




};

#define SeqItem WOKernel_DBMSID
#define SeqItem_hxx <WOKernel_DBMSID.hxx>
#define TCollection_SequenceNode WOKernel_SequenceNodeOfSequenceOfDBMSID
#define TCollection_SequenceNode_hxx <WOKernel_SequenceNodeOfSequenceOfDBMSID.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKernel_SequenceNodeOfSequenceOfDBMSID
#define TCollection_SequenceNode_Type_() WOKernel_SequenceNodeOfSequenceOfDBMSID_Type_()
#define TCollection_Sequence WOKernel_SequenceOfDBMSID
#define TCollection_Sequence_hxx <WOKernel_SequenceOfDBMSID.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
