// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_UnitGraph_HeaderFile
#define _WOKernel_UnitGraph_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKernel_UnitGraph_HeaderFile
#include <Handle_WOKernel_UnitGraph.hxx>
#endif

#ifndef _Handle_WOKernel_Locator_HeaderFile
#include <Handle_WOKernel_Locator.hxx>
#endif
#ifndef _WOKTools_DataMapOfHAsciiStringOfHSequenceOfHAsciiString_HeaderFile
#include <WOKTools_DataMapOfHAsciiStringOfHSequenceOfHAsciiString.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
#ifndef _Handle_WOKernel_Workbench_HeaderFile
#include <Handle_WOKernel_Workbench.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
class WOKernel_Locator;
class WOKernel_Workbench;
class TCollection_HAsciiString;
class TColStd_HSequenceOfHAsciiString;



class WOKernel_UnitGraph : public MMgt_TShared {

public:

  
  Standard_EXPORT   WOKernel_UnitGraph(const Handle(WOKernel_Workbench)& awb);
  
  Standard_EXPORT   WOKernel_UnitGraph(const Handle(WOKernel_Locator)& alocator);
  
  Standard_EXPORT     Standard_Boolean Contains(const Handle(TCollection_HAsciiString)& aname) const;
  
  Standard_EXPORT     void Add(const Handle(TCollection_HAsciiString)& aname,const Handle(TColStd_HSequenceOfHAsciiString)& suppliers) ;
  
  Standard_EXPORT     void Add(const Handle(TCollection_HAsciiString)& aname,const Handle(TCollection_HAsciiString)& asupplier) ;
  
  Standard_EXPORT     void Remove(const Handle(TCollection_HAsciiString)& aname) ;
  
  Standard_EXPORT    const Handle_TColStd_HSequenceOfHAsciiString& Suppliers(const Handle(TCollection_HAsciiString)& aname) const;
  
  Standard_EXPORT     Handle_WOKernel_Locator Locator() const;




  DEFINE_STANDARD_RTTI(WOKernel_UnitGraph)

protected:




private: 


Handle_WOKernel_Locator mylocator;
WOKTools_DataMapOfHAsciiStringOfHSequenceOfHAsciiString myUDMap;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
