// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_DBMSID_HeaderFile
#define _WOKernel_DBMSID_HeaderFile

//! liste les stations supportees par WOK <br>
enum WOKernel_DBMSID {
WOKernel_DFLT,
WOKernel_OBJY,
WOKernel_OBJS,
WOKernel_UnknownDBMS
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
