// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_SCMapOfSortedClientsFromIterator_HeaderFile
#define _WOKernel_SCMapOfSortedClientsFromIterator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BasicMap_HeaderFile
#include <TCollection_BasicMap.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Handle_WOKernel_IndexedDataMapNodeOfSCMapOfSortedClientsFromIterator_HeaderFile
#include <Handle_WOKernel_IndexedDataMapNodeOfSCMapOfSortedClientsFromIterator.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_DomainError;
class Standard_OutOfRange;
class Standard_NoSuchObject;
class TCollection_HAsciiString;
class WOKernel_HAsciiStringHasher;
class WOKernel_IndexedDataMapNodeOfSCMapOfSortedClientsFromIterator;



class WOKernel_SCMapOfSortedClientsFromIterator  : public TCollection_BasicMap {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   WOKernel_SCMapOfSortedClientsFromIterator(const Standard_Integer NbBuckets = 1);
  
  Standard_EXPORT     WOKernel_SCMapOfSortedClientsFromIterator& Assign(const WOKernel_SCMapOfSortedClientsFromIterator& Other) ;
    WOKernel_SCMapOfSortedClientsFromIterator& operator =(const WOKernel_SCMapOfSortedClientsFromIterator& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void ReSize(const Standard_Integer NbBuckets) ;
  
  Standard_EXPORT     void Clear() ;
~WOKernel_SCMapOfSortedClientsFromIterator()
{
  Clear();
}
  
  Standard_EXPORT     Standard_Integer Add(const Handle(TCollection_HAsciiString)& K,const Standard_Integer& I) ;
  
  Standard_EXPORT     void Substitute(const Standard_Integer I,const Handle(TCollection_HAsciiString)& K,const Standard_Integer& T) ;
  
  Standard_EXPORT     void RemoveLast() ;
  
  Standard_EXPORT     Standard_Boolean Contains(const Handle(TCollection_HAsciiString)& K) const;
  
  Standard_EXPORT    const Handle_TCollection_HAsciiString& FindKey(const Standard_Integer I) const;
  
  Standard_EXPORT    const Standard_Integer& FindFromIndex(const Standard_Integer I) const;
   const Standard_Integer& operator ()(const Standard_Integer I) const
{
  return FindFromIndex(I);
}
  
  Standard_EXPORT     Standard_Integer& ChangeFromIndex(const Standard_Integer I) ;
    Standard_Integer& operator ()(const Standard_Integer I) 
{
  return ChangeFromIndex(I);
}
  
  Standard_EXPORT     Standard_Integer FindIndex(const Handle(TCollection_HAsciiString)& K) const;
  
  Standard_EXPORT    const Standard_Integer& FindFromKey(const Handle(TCollection_HAsciiString)& K) const;
  
  Standard_EXPORT     Standard_Integer& ChangeFromKey(const Handle(TCollection_HAsciiString)& K) ;





protected:





private:

  
  Standard_EXPORT   WOKernel_SCMapOfSortedClientsFromIterator(const WOKernel_SCMapOfSortedClientsFromIterator& Other);




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
