// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKernel_FileTypeIterator_HeaderFile
#define _WOKernel_FileTypeIterator_HeaderFile

#ifndef _WOKernel_DataMapIteratorOfDataMapOfFileType_HeaderFile
#include <WOKernel_DataMapIteratorOfDataMapOfFileType.hxx>
#endif

typedef WOKernel_DataMapIteratorOfDataMapOfFileType WOKernel_FileTypeIterator;


#define WOKernel_FileTypeIterator_Type_() WOKernel_DataMapIteratorOfDataMapOfFileType_Type_()

#endif
