// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKMake_SequenceNodeOfSequenceOfOutputFile_HeaderFile
#define _WOKMake_SequenceNodeOfSequenceOfOutputFile_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKMake_SequenceNodeOfSequenceOfOutputFile_HeaderFile
#include <Handle_WOKMake_SequenceNodeOfSequenceOfOutputFile.hxx>
#endif

#ifndef _Handle_WOKMake_OutputFile_HeaderFile
#include <Handle_WOKMake_OutputFile.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class WOKMake_OutputFile;
class WOKMake_SequenceOfOutputFile;



class WOKMake_SequenceNodeOfSequenceOfOutputFile : public TCollection_SeqNode {

public:

  
      WOKMake_SequenceNodeOfSequenceOfOutputFile(const Handle(WOKMake_OutputFile)& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Handle_WOKMake_OutputFile& Value() const;




  DEFINE_STANDARD_RTTI(WOKMake_SequenceNodeOfSequenceOfOutputFile)

protected:




private: 


Handle_WOKMake_OutputFile myValue;


};

#define SeqItem Handle_WOKMake_OutputFile
#define SeqItem_hxx <WOKMake_OutputFile.hxx>
#define TCollection_SequenceNode WOKMake_SequenceNodeOfSequenceOfOutputFile
#define TCollection_SequenceNode_hxx <WOKMake_SequenceNodeOfSequenceOfOutputFile.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKMake_SequenceNodeOfSequenceOfOutputFile
#define TCollection_SequenceNode_Type_() WOKMake_SequenceNodeOfSequenceOfOutputFile_Type_()
#define TCollection_Sequence WOKMake_SequenceOfOutputFile
#define TCollection_Sequence_hxx <WOKMake_SequenceOfOutputFile.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
