// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKMake_TriggerStep_HeaderFile
#define _WOKMake_TriggerStep_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKMake_TriggerStep_HeaderFile
#include <Handle_WOKMake_TriggerStep.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _WOKMake_Step_HeaderFile
#include <WOKMake_Step.hxx>
#endif
#ifndef _Handle_WOKMake_BuildProcess_HeaderFile
#include <Handle_WOKMake_BuildProcess.hxx>
#endif
#ifndef _Handle_WOKernel_DevUnit_HeaderFile
#include <Handle_WOKernel_DevUnit.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_WOKMake_InputFile_HeaderFile
#include <Handle_WOKMake_InputFile.hxx>
#endif
#ifndef _Handle_WOKMake_OutputFile_HeaderFile
#include <Handle_WOKMake_OutputFile.hxx>
#endif
#ifndef _Handle_WOKMake_HSequenceOfInputFile_HeaderFile
#include <Handle_WOKMake_HSequenceOfInputFile.hxx>
#endif
class TCollection_HAsciiString;
class WOKMake_BuildProcess;
class WOKernel_DevUnit;
class WOKMake_InputFile;
class WOKMake_OutputFile;
class WOKMake_HSequenceOfInputFile;



class WOKMake_TriggerStep : public WOKMake_Step {

public:

  
  Standard_EXPORT   WOKMake_TriggerStep(const Handle(WOKMake_BuildProcess)& aprocess,const Handle(WOKernel_DevUnit)& aunit,const Handle(TCollection_HAsciiString)& acode,const Standard_Boolean checked,const Standard_Boolean hidden);
  
  Standard_EXPORT   static  Handle_WOKMake_TriggerStep& CurrentTriggerStep() ;
  
  Standard_EXPORT     void SetName(const Handle(TCollection_HAsciiString)& aname) ;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Name() const;
  
  Standard_EXPORT     void AddInputFile(const Handle(WOKMake_InputFile)& inputfile) ;
  
  Standard_EXPORT     Handle_WOKMake_InputFile GetInputFile(const Handle(TCollection_HAsciiString)& anid) const;
  
  Standard_EXPORT     void AddOutputFile(const Handle(WOKMake_OutputFile)& Outputfile) ;
  
  Standard_EXPORT     Handle_WOKMake_OutputFile GetOutputFile(const Handle(TCollection_HAsciiString)& anid) const;




  DEFINE_STANDARD_RTTI(WOKMake_TriggerStep)

protected:

  
  Standard_EXPORT   virtual  Handle_TCollection_HAsciiString AdmFileType() const;
  
  Standard_EXPORT   virtual  Handle_TCollection_HAsciiString OutputDirTypeName() const;
  
  Standard_EXPORT   virtual  Standard_Boolean HandleInputFile(const Handle(WOKMake_InputFile)& anitem) ;
  
  Standard_EXPORT   virtual  void Init() ;
  
  Standard_EXPORT   virtual  void Terminate() ;



private: 

  //! Executes step <br>
//!          Computes output files <br>
  Standard_EXPORT   virtual  void Execute(const Handle(WOKMake_HSequenceOfInputFile)& execlist) ;

Handle_TCollection_HAsciiString myname;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
