// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKOrbix_IDLCompilerIterator_HeaderFile
#define _WOKOrbix_IDLCompilerIterator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Handle_WOKUtils_HSequenceOfPath_HeaderFile
#include <Handle_WOKUtils_HSequenceOfPath.hxx>
#endif
#ifndef _WOKBuilder_ToolInShellIterator_HeaderFile
#include <WOKBuilder_ToolInShellIterator.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_WOKBuilder_HSequenceOfToolInShell_HeaderFile
#include <Handle_WOKBuilder_HSequenceOfToolInShell.hxx>
#endif
#ifndef _Handle_WOKUtils_Shell_HeaderFile
#include <Handle_WOKUtils_Shell.hxx>
#endif
#ifndef _Handle_WOKUtils_Path_HeaderFile
#include <Handle_WOKUtils_Path.hxx>
#endif
#ifndef _Handle_WOKBuilder_ToolInShell_HeaderFile
#include <Handle_WOKBuilder_ToolInShell.hxx>
#endif
#ifndef _WOKBuilder_BuildStatus_HeaderFile
#include <WOKBuilder_BuildStatus.hxx>
#endif
#ifndef _Handle_WOKOrbix_IDLFile_HeaderFile
#include <Handle_WOKOrbix_IDLFile.hxx>
#endif
class WOKUtils_HSequenceOfPath;
class TCollection_HAsciiString;
class WOKUtils_Param;
class WOKBuilder_HSequenceOfToolInShell;
class WOKUtils_Shell;
class WOKUtils_Path;
class WOKBuilder_ToolInShell;
class WOKOrbix_IDLFile;



class WOKOrbix_IDLCompilerIterator  : public WOKBuilder_ToolInShellIterator {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   WOKOrbix_IDLCompilerIterator(const Handle(TCollection_HAsciiString)& toolgroup,const WOKUtils_Param& params);
  
  Standard_EXPORT   WOKOrbix_IDLCompilerIterator(const Handle(WOKBuilder_HSequenceOfToolInShell)& tools);
  
  Standard_EXPORT   WOKOrbix_IDLCompilerIterator(const Handle(TCollection_HAsciiString)& toolgroup,const Handle(WOKUtils_Shell)& ashell,const Handle(WOKUtils_Path)& adir,const Handle(WOKUtils_HSequenceOfPath)& incdirs,const WOKUtils_Param& params);
  
  Standard_EXPORT     void Init(const Handle(WOKUtils_Shell)& ashell,const Handle(WOKUtils_Path)& adir,const Handle(WOKUtils_HSequenceOfPath)& incdirs) ;
  
  Standard_EXPORT     void SetIncludeDirectories(const Handle(WOKUtils_HSequenceOfPath)& incdirs) ;
  
  Standard_EXPORT     Handle_WOKUtils_HSequenceOfPath IncludeDirectories() const;
  
  Standard_EXPORT   virtual  Handle_WOKBuilder_ToolInShell GetTool(const Handle(TCollection_HAsciiString)& aname,const WOKUtils_Param& params) const;
  
  Standard_EXPORT     WOKBuilder_BuildStatus Execute(const Handle(WOKOrbix_IDLFile)& anidl) ;





protected:





private:



Handle_WOKUtils_HSequenceOfPath myincdirs;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
