// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKStep_LibUnCompress_HeaderFile
#define _WOKStep_LibUnCompress_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKStep_LibUnCompress_HeaderFile
#include <Handle_WOKStep_LibUnCompress.hxx>
#endif

#ifndef _WOKMake_Step_HeaderFile
#include <WOKMake_Step.hxx>
#endif
#ifndef _Handle_WOKMake_BuildProcess_HeaderFile
#include <Handle_WOKMake_BuildProcess.hxx>
#endif
#ifndef _Handle_WOKernel_DevUnit_HeaderFile
#include <Handle_WOKernel_DevUnit.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_WOKMake_InputFile_HeaderFile
#include <Handle_WOKMake_InputFile.hxx>
#endif
#ifndef _Handle_WOKMake_HSequenceOfInputFile_HeaderFile
#include <Handle_WOKMake_HSequenceOfInputFile.hxx>
#endif
class WOKMake_BuildProcess;
class WOKernel_DevUnit;
class TCollection_HAsciiString;
class WOKMake_InputFile;
class WOKMake_HSequenceOfInputFile;



class WOKStep_LibUnCompress : public WOKMake_Step {

public:

  
  Standard_EXPORT   WOKStep_LibUnCompress(const Handle(WOKMake_BuildProcess)& abp,const Handle(WOKernel_DevUnit)& aunit,const Handle(TCollection_HAsciiString)& acode,const Standard_Boolean checked,const Standard_Boolean hidden);




  DEFINE_STANDARD_RTTI(WOKStep_LibUnCompress)

protected:

  
  Standard_EXPORT   virtual  Handle_TCollection_HAsciiString AdmFileType() const;
  
  Standard_EXPORT   virtual  Handle_TCollection_HAsciiString OutputDirTypeName() const;
  //! 1 - Adds File In list if file is compilable or an admfile <br>
//!          2 - Sets Build Flag if file is a compilable <br>
  Standard_EXPORT   virtual  Standard_Boolean HandleInputFile(const Handle(WOKMake_InputFile)& item) ;



private: 

  
  Standard_EXPORT   virtual  void Execute(const Handle(WOKMake_HSequenceOfInputFile)& execlist) ;



};





// other Inline functions and methods (like "C++: function call" methods)


#endif
