// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKStep_TransitiveTKReplace_HeaderFile
#define _WOKStep_TransitiveTKReplace_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKStep_TransitiveTKReplace_HeaderFile
#include <Handle_WOKStep_TransitiveTKReplace.hxx>
#endif

#ifndef _WOKStep_TKReplace_HeaderFile
#include <WOKStep_TKReplace.hxx>
#endif
#ifndef _Handle_WOKMake_BuildProcess_HeaderFile
#include <Handle_WOKMake_BuildProcess.hxx>
#endif
#ifndef _Handle_WOKernel_DevUnit_HeaderFile
#include <Handle_WOKernel_DevUnit.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
class WOKMake_BuildProcess;
class WOKernel_DevUnit;
class TCollection_HAsciiString;
class TColStd_HSequenceOfHAsciiString;



class WOKStep_TransitiveTKReplace : public WOKStep_TKReplace {

public:

  
  Standard_EXPORT   WOKStep_TransitiveTKReplace(const Handle(WOKMake_BuildProcess)& abp,const Handle(WOKernel_DevUnit)& aunit,const Handle(TCollection_HAsciiString)& acode,const Standard_Boolean checked,const Standard_Boolean hidden);




  DEFINE_STANDARD_RTTI(WOKStep_TransitiveTKReplace)

protected:

  
  Standard_EXPORT   virtual  Handle_TColStd_HSequenceOfHAsciiString ComputeDependency(const Handle(TCollection_HAsciiString)& code,const Handle(TColStd_HSequenceOfHAsciiString)& adirectlist) const;



private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
