// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKStep_Extract_HeaderFile
#define _WOKStep_Extract_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKStep_Extract_HeaderFile
#include <Handle_WOKStep_Extract.hxx>
#endif

#ifndef _Handle_WOKBuilder_MSExtractor_HeaderFile
#include <Handle_WOKBuilder_MSExtractor.hxx>
#endif
#ifndef _WOKStep_MSStep_HeaderFile
#include <WOKStep_MSStep.hxx>
#endif
#ifndef _Handle_WOKMake_BuildProcess_HeaderFile
#include <Handle_WOKMake_BuildProcess.hxx>
#endif
#ifndef _Handle_WOKernel_DevUnit_HeaderFile
#include <Handle_WOKernel_DevUnit.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_WOKMake_InputFile_HeaderFile
#include <Handle_WOKMake_InputFile.hxx>
#endif
#ifndef _Handle_WOKMake_HSequenceOfInputFile_HeaderFile
#include <Handle_WOKMake_HSequenceOfInputFile.hxx>
#endif
class WOKBuilder_MSExtractor;
class WOKMake_BuildProcess;
class WOKernel_DevUnit;
class TCollection_HAsciiString;
class WOKMake_InputFile;
class WOKMake_HSequenceOfInputFile;



class WOKStep_Extract : public WOKStep_MSStep {

public:

  
  Standard_EXPORT     void SetExtractor(const Handle(WOKBuilder_MSExtractor)& anextractor) ;
  
  Standard_EXPORT     Handle_WOKBuilder_MSExtractor Extractor() const;




  DEFINE_STANDARD_RTTI(WOKStep_Extract)

protected:

  
  Standard_EXPORT   WOKStep_Extract(const Handle(WOKMake_BuildProcess)& abp,const Handle(WOKernel_DevUnit)& aunit,const Handle(TCollection_HAsciiString)& acode,const Standard_Boolean checked,const Standard_Boolean hidden);
  
  Standard_EXPORT   virtual  Handle_TCollection_HAsciiString AdmFileType() const;
  
  Standard_EXPORT   virtual  Handle_TCollection_HAsciiString OutputDirTypeName() const;
  
  Standard_EXPORT   virtual  Standard_Boolean HandleInputFile(const Handle(WOKMake_InputFile)& item) ;



private: 

  
  Standard_EXPORT   virtual  void Execute(const Handle(WOKMake_HSequenceOfInputFile)& execlist) ;

Handle_WOKBuilder_MSExtractor myextractor;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
