// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKStep_WNTCollect_HeaderFile
#define _WOKStep_WNTCollect_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKStep_WNTCollect_HeaderFile
#include <Handle_WOKStep_WNTCollect.hxx>
#endif

#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _WOKTools_IndexedMapOfHAsciiString_HeaderFile
#include <WOKTools_IndexedMapOfHAsciiString.hxx>
#endif
#ifndef _WOKTools_MapOfHAsciiString_HeaderFile
#include <WOKTools_MapOfHAsciiString.hxx>
#endif
#ifndef _Handle_TColStd_HArray2OfBoolean_HeaderFile
#include <Handle_TColStd_HArray2OfBoolean.hxx>
#endif
#ifndef _WOKMake_Step_HeaderFile
#include <WOKMake_Step.hxx>
#endif
#ifndef _Handle_WOKMake_BuildProcess_HeaderFile
#include <Handle_WOKMake_BuildProcess.hxx>
#endif
#ifndef _Handle_WOKernel_DevUnit_HeaderFile
#include <Handle_WOKernel_DevUnit.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_WOKBuilder_WNTCollector_HeaderFile
#include <Handle_WOKBuilder_WNTCollector.hxx>
#endif
#ifndef _Handle_WOKBuilder_HSequenceOfObjectFile_HeaderFile
#include <Handle_WOKBuilder_HSequenceOfObjectFile.hxx>
#endif
#ifndef _Handle_WOKMake_HSequenceOfInputFile_HeaderFile
#include <Handle_WOKMake_HSequenceOfInputFile.hxx>
#endif
#ifndef _Handle_WOKMake_OutputFile_HeaderFile
#include <Handle_WOKMake_OutputFile.hxx>
#endif
class TColStd_HArray2OfBoolean;
class WOKMake_BuildProcess;
class WOKernel_DevUnit;
class TCollection_HAsciiString;
class WOKBuilder_WNTCollector;
class WOKBuilder_HSequenceOfObjectFile;
class WOKMake_HSequenceOfInputFile;
class WOKMake_OutputFile;



class WOKStep_WNTCollect : public WOKMake_Step {

public:





  DEFINE_STANDARD_RTTI(WOKStep_WNTCollect)

protected:

  //! provides initialization <br>
  Standard_EXPORT   WOKStep_WNTCollect(const Handle(WOKMake_BuildProcess)& abp,const Handle(WOKernel_DevUnit)& aUnit,const Handle(TCollection_HAsciiString)& aCode,const Standard_Boolean checked,const Standard_Boolean hidden);
  //! returns type of ADM file <br>
  Standard_EXPORT     Handle_TCollection_HAsciiString AdmFileType() const;
  //! computes build tool <br>
  Standard_EXPORT   virtual  Handle_WOKBuilder_WNTCollector ComputeTool()  = 0;
  //! computes object list to build <br>
  Standard_EXPORT   virtual  Handle_WOKBuilder_HSequenceOfObjectFile ComputeObjectList(const Handle(WOKMake_HSequenceOfInputFile)& anInput) ;
  //! returns output directoty type name <br>
  Standard_EXPORT     Handle_TCollection_HAsciiString OutputDirTypeName() const;
  
  Standard_EXPORT     void CompleteExecList(const Handle(WOKMake_HSequenceOfInputFile)& anExecList) ;
  
  Standard_EXPORT     Standard_Boolean HandleOutputFile(const Handle(WOKMake_OutputFile)& aFile) ;



private: 


Standard_Boolean myInitFlag;
WOKTools_IndexedMapOfHAsciiString myuds;
WOKTools_IndexedMapOfHAsciiString mytks;
WOKTools_MapOfHAsciiString myautorized;
Standard_Boolean myauthlist;
WOKTools_MapOfHAsciiString mytreated;
Handle_TColStd_HArray2OfBoolean mymatrix;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
