// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKTools_EnvValue_HeaderFile
#define _WOKTools_EnvValue_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKTools_EnvValue_HeaderFile
#include <Handle_WOKTools_EnvValue.hxx>
#endif

#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _WOKTools_ReturnValue_HeaderFile
#include <WOKTools_ReturnValue.hxx>
#endif
class TCollection_HAsciiString;



class WOKTools_EnvValue : public WOKTools_ReturnValue {

public:

  //! Creates an EnvValue to Set in Environment <br>
  Standard_EXPORT   WOKTools_EnvValue(const Handle(TCollection_HAsciiString)& avarname,const Handle(TCollection_HAsciiString)& avalue);
  //! Creates an EnvValue to UnSet Environment <br>
  Standard_EXPORT   WOKTools_EnvValue(const Handle(TCollection_HAsciiString)& avarname);
  
  Standard_EXPORT     void SetName(const Handle(TCollection_HAsciiString)& aname) ;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Name() const;
  
  Standard_EXPORT     void SetValue(const Handle(TCollection_HAsciiString)& avalue) ;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Value() const;
  
  Standard_EXPORT     Standard_Boolean ToSet() const;




  DEFINE_STANDARD_RTTI(WOKTools_EnvValue)

protected:




private: 


Standard_Boolean myflag;
Handle_TCollection_HAsciiString myname;
Handle_TCollection_HAsciiString myvalue;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
