// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKTools_SequenceNodeOfSequenceOfReturnValue_HeaderFile
#define _WOKTools_SequenceNodeOfSequenceOfReturnValue_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKTools_SequenceNodeOfSequenceOfReturnValue_HeaderFile
#include <Handle_WOKTools_SequenceNodeOfSequenceOfReturnValue.hxx>
#endif

#ifndef _Handle_WOKTools_ReturnValue_HeaderFile
#include <Handle_WOKTools_ReturnValue.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class WOKTools_ReturnValue;
class WOKTools_SequenceOfReturnValue;



class WOKTools_SequenceNodeOfSequenceOfReturnValue : public TCollection_SeqNode {

public:

  
      WOKTools_SequenceNodeOfSequenceOfReturnValue(const Handle(WOKTools_ReturnValue)& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Handle_WOKTools_ReturnValue& Value() const;




  DEFINE_STANDARD_RTTI(WOKTools_SequenceNodeOfSequenceOfReturnValue)

protected:




private: 


Handle_WOKTools_ReturnValue myValue;


};

#define SeqItem Handle_WOKTools_ReturnValue
#define SeqItem_hxx <WOKTools_ReturnValue.hxx>
#define TCollection_SequenceNode WOKTools_SequenceNodeOfSequenceOfReturnValue
#define TCollection_SequenceNode_hxx <WOKTools_SequenceNodeOfSequenceOfReturnValue.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKTools_SequenceNodeOfSequenceOfReturnValue
#define TCollection_SequenceNode_Type_() WOKTools_SequenceNodeOfSequenceOfReturnValue_Type_()
#define TCollection_Sequence WOKTools_SequenceOfReturnValue
#define TCollection_Sequence_hxx <WOKTools_SequenceOfReturnValue.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
