// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKTools_InterpFileValue_HeaderFile
#define _WOKTools_InterpFileValue_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKTools_InterpFileValue_HeaderFile
#include <Handle_WOKTools_InterpFileValue.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _WOKTools_InterpFileType_HeaderFile
#include <WOKTools_InterpFileType.hxx>
#endif
#ifndef _WOKTools_ReturnValue_HeaderFile
#include <WOKTools_ReturnValue.hxx>
#endif
class TCollection_HAsciiString;



class WOKTools_InterpFileValue : public WOKTools_ReturnValue {

public:

  
  Standard_EXPORT   WOKTools_InterpFileValue(const Handle(TCollection_HAsciiString)& afile,const WOKTools_InterpFileType atype = WOKTools_CShell);
  
  Standard_EXPORT   static  Handle_TCollection_HAsciiString InterpFormat(const WOKTools_InterpFileType atype) ;
  
  Standard_EXPORT   static  WOKTools_InterpFileType InterpType(const Handle(TCollection_HAsciiString)& aformat) ;
  
  Standard_EXPORT   static  Handle_TCollection_HAsciiString FileName(const WOKTools_InterpFileType atype,const Handle(TCollection_HAsciiString)& abasename) ;
  
  Standard_EXPORT     void SetFile(const Handle(TCollection_HAsciiString)& afile) ;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString File() const;
  
  Standard_EXPORT     void SetInterpType(const WOKTools_InterpFileType atype) ;
  
  Standard_EXPORT     WOKTools_InterpFileType InterpType() const;




  DEFINE_STANDARD_RTTI(WOKTools_InterpFileValue)

protected:




private: 


Handle_TCollection_HAsciiString myfile;
WOKTools_InterpFileType mytype;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
