// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKUnix_StackIteratorOfStackOfDir_HeaderFile
#define _WOKUnix_StackIteratorOfStackOfDir_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _WOKUnix_Dir_HeaderFile
#include <WOKUnix_Dir.hxx>
#endif
#ifndef _Handle_WOKUnix_StackNodeOfStackOfDir_HeaderFile
#include <Handle_WOKUnix_StackNodeOfStackOfDir.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class WOKUnix_StackOfDir;
class WOKUnix_StackNodeOfStackOfDir;



class WOKUnix_StackIteratorOfStackOfDir  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   WOKUnix_StackIteratorOfStackOfDir();
  
  Standard_EXPORT   WOKUnix_StackIteratorOfStackOfDir(const WOKUnix_StackOfDir& S);
  
  Standard_EXPORT     void Initialize(const WOKUnix_StackOfDir& S) ;
  
        Standard_Boolean More() const;
  
  Standard_EXPORT     void Next() ;
  
  Standard_EXPORT    const WOKUnix_Dir& Value() const;





protected:





private:



Standard_Address current;


};

#define Item WOKUnix_Dir
#define Item_hxx <WOKUnix_Dir.hxx>
#define TCollection_StackNode WOKUnix_StackNodeOfStackOfDir
#define TCollection_StackNode_hxx <WOKUnix_StackNodeOfStackOfDir.hxx>
#define TCollection_StackIterator WOKUnix_StackIteratorOfStackOfDir
#define TCollection_StackIterator_hxx <WOKUnix_StackIteratorOfStackOfDir.hxx>
#define Handle_TCollection_StackNode Handle_WOKUnix_StackNodeOfStackOfDir
#define TCollection_StackNode_Type_() WOKUnix_StackNodeOfStackOfDir_Type_()
#define TCollection_Stack WOKUnix_StackOfDir
#define TCollection_Stack_hxx <WOKUnix_StackOfDir.hxx>

#include <TCollection_StackIterator.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_StackNode
#undef TCollection_StackNode_hxx
#undef TCollection_StackIterator
#undef TCollection_StackIterator_hxx
#undef Handle_TCollection_StackNode
#undef TCollection_StackNode_Type_
#undef TCollection_Stack
#undef TCollection_Stack_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
