// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKUnix_OutErrOutput_HeaderFile
#define _WOKUnix_OutErrOutput_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKUnix_OutErrOutput_HeaderFile
#include <Handle_WOKUnix_OutErrOutput.hxx>
#endif

#ifndef _Handle_WOKUnix_Buffer_HeaderFile
#include <Handle_WOKUnix_Buffer.hxx>
#endif
#ifndef _WOKUnix_ProcessOutput_HeaderFile
#include <WOKUnix_ProcessOutput.hxx>
#endif
#ifndef _WOKUnix_PopenBufferMode_HeaderFile
#include <WOKUnix_PopenBufferMode.hxx>
#endif
#ifndef _Handle_TColStd_HSequenceOfHAsciiString_HeaderFile
#include <Handle_TColStd_HSequenceOfHAsciiString.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _WOKUnix_Timeval_HeaderFile
#include <WOKUnix_Timeval.hxx>
#endif
#ifndef _WOKUnix_FDSet_HeaderFile
#include <WOKUnix_FDSet.hxx>
#endif
class WOKUnix_Buffer;
class WOKUnix_FDescr;
class TColStd_HSequenceOfHAsciiString;



class WOKUnix_OutErrOutput : public WOKUnix_ProcessOutput {

public:

  
  Standard_EXPORT   WOKUnix_OutErrOutput();
  
  Standard_EXPORT   WOKUnix_OutErrOutput(const WOKUnix_FDescr& aoutfd,const WOKUnix_FDescr& aerrfd,const WOKUnix_PopenBufferMode amode);
  
  Standard_EXPORT   WOKUnix_OutErrOutput(const Handle(WOKUnix_OutErrOutput)& anoutput,const WOKUnix_PopenBufferMode amode);
  
  Standard_EXPORT   virtual  void Clear() const;
  
  Standard_EXPORT   virtual  Handle_TColStd_HSequenceOfHAsciiString Echo() const;
  
  Standard_EXPORT   virtual  Handle_TColStd_HSequenceOfHAsciiString Errors() const;
  
  Standard_EXPORT   virtual  void Select(Standard_Integer& afdmax,WOKUnix_Timeval& atimeout,WOKUnix_FDSet& aset) const;
  
  Standard_EXPORT   virtual  void Acquit(const Standard_Integer selectstatus,const WOKUnix_FDSet& aset) const;
  
  Standard_EXPORT   virtual  void Close() ;




  DEFINE_STANDARD_RTTI(WOKUnix_OutErrOutput)

protected:




private: 


Handle_WOKUnix_Buffer myout;
Handle_WOKUnix_Buffer myerr;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
