// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKUtils_ParamItem_HeaderFile
#define _WOKUtils_ParamItem_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Standard_CString_HeaderFile
#include <Standard_CString.hxx>
#endif
class TCollection_HAsciiString;
class Standard_ProgramError;



class WOKUtils_ParamItem  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   WOKUtils_ParamItem();
  
  Standard_EXPORT   WOKUtils_ParamItem(const Handle(TCollection_HAsciiString)& aname,const Handle(TCollection_HAsciiString)& avalue);
  
  Standard_EXPORT   WOKUtils_ParamItem(const Standard_CString aname,const Standard_CString avalue);
  
  Standard_EXPORT     void SetName(const Handle(TCollection_HAsciiString)& aname) ;
  
  Standard_EXPORT     void SetValue(const Handle(TCollection_HAsciiString)& avalue) ;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Name() const;
  
  Standard_EXPORT     Handle_TCollection_HAsciiString Value() const;





protected:





private:



Handle_TCollection_HAsciiString myname;
Handle_TCollection_HAsciiString myvalue;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
