// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKUnix_PopenBufferMode_HeaderFile
#define _WOKUnix_PopenBufferMode_HeaderFile


enum WOKUnix_PopenBufferMode {
WOKUnix_POPEN_BUFFERED,
WOKUnix_POPEN_IMMEDIATE,
WOKUnix_POPEN_ECHOIFBLOCKED
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
