// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKUnix_Extension_HeaderFile
#define _WOKUnix_Extension_HeaderFile


enum WOKUnix_Extension {
WOKUnix_CFile,
WOKUnix_HFile,
WOKUnix_CDLFile,
WOKUnix_ODLFile,
WOKUnix_IDLFile,
WOKUnix_CXXFile,
WOKUnix_HXXFile,
WOKUnix_IXXFile,
WOKUnix_JXXFile,
WOKUnix_LXXFile,
WOKUnix_GXXFile,
WOKUnix_INCFile,
WOKUnix_PXXFile,
WOKUnix_F77File,
WOKUnix_CSHFile,
WOKUnix_DBFile,
WOKUnix_FDDBFile,
WOKUnix_DDLFile,
WOKUnix_HO2File,
WOKUnix_LibSchemaFile,
WOKUnix_AppSchemaFile,
WOKUnix_LexFile,
WOKUnix_YaccFile,
WOKUnix_PSWFile,
WOKUnix_LWSFile,
WOKUnix_TemplateFile,
WOKUnix_ObjectFile,
WOKUnix_MFile,
WOKUnix_CompressedFile,
WOKUnix_ArchiveFile,
WOKUnix_DSOFile,
WOKUnix_DATFile,
WOKUnix_LispFile,
WOKUnix_IconFile,
WOKUnix_TextFile,
WOKUnix_TarFile,
WOKUnix_LIBFile,
WOKUnix_DEFile,
WOKUnix_RCFile,
WOKUnix_RESFile,
WOKUnix_IMPFile,
WOKUnix_EXPFile,
WOKUnix_UnknownFile,
WOKUnix_NoExtFile
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
