// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WOKUnix_SyncStatus_HeaderFile
#define _WOKUnix_SyncStatus_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_WOKUnix_SyncStatus_HeaderFile
#include <Handle_WOKUnix_SyncStatus.hxx>
#endif

#ifndef _WOKUnix_ShellStatus_HeaderFile
#include <WOKUnix_ShellStatus.hxx>
#endif
#ifndef _Handle_WOKUnix_Shell_HeaderFile
#include <Handle_WOKUnix_Shell.hxx>
#endif
class TCollection_AsciiString;
class WOKUnix_Shell;



class WOKUnix_SyncStatus : public WOKUnix_ShellStatus {

public:

  
  Standard_EXPORT   WOKUnix_SyncStatus();
  
  Standard_EXPORT   WOKUnix_SyncStatus(const TCollection_AsciiString& apath);
  
  Standard_EXPORT   virtual  void EndCmd(const Handle(WOKUnix_Shell)& ashell) ;
  
  Standard_EXPORT   virtual  void Sync(const Handle(WOKUnix_Shell)& ashell) ;
  
  Standard_EXPORT   virtual  void Reset(const Handle(WOKUnix_Shell)& ashell) ;




  DEFINE_STANDARD_RTTI(WOKUnix_SyncStatus)

protected:




private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
