/*
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.audiomanager.client.voicechat;

import java.awt.event.ActionListener;
import java.util.ResourceBundle;

/**
 *
 * @author nsimpson
 * @author Ronny Standtke <ronny.standtke@fhnw.ch>
 */
public class PrivacyPanel extends javax.swing.JPanel {

    private static final ResourceBundle BUNDLE = ResourceBundle.getBundle(
            "org/jdesktop/wonderland/modules/audiomanager/client/resources/Bundle");
    public static final String SECRET_DESCRIPTION =
            BUNDLE.getString("Secret_Description");
    public static final String PRIVATE_DESCRIPTION =
            BUNDLE.getString("Private_Description");
    public static final String PUBLIC_DESCRIPTION =
            BUNDLE.getString("Public_Description");

    public PrivacyPanel() {
        initComponents();
        validate();
    }

    public void addSecretRadioButtonActionListener(
            ActionListener actionListener) {
        secretRadioButton.addActionListener(actionListener);
    }

    public void removeSecretRadioButtonActionListener(
            ActionListener actionListener) {
        secretRadioButton.removeActionListener(actionListener);
    }

    public void addPrivateRadioButtonActionListener(
            ActionListener actionListener) {
        privateRadioButton.addActionListener(actionListener);
    }

    public void removePrivateRadioButtonActionListener(
            ActionListener actionListener) {
        privateRadioButton.removeActionListener(actionListener);
    }

    public void addPublicRadioButtonActionListener(
            ActionListener actionListener) {
        //publicRadioButton.addActionListener(actionListener);
    }

    public void removePublicPrivateRadioButtonActionListener(
            ActionListener actionListener) {
        //publicRadioButton.removeActionListener(actionListener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        privateRadioButton = new javax.swing.JRadioButton();
        secretRadioButton = new javax.swing.JRadioButton();
        privacyDescriptionLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 57));
        setMinimumSize(new java.awt.Dimension(287, 57));
        setName("Form"); // NOI18N

        buttonGroup1.add(privateRadioButton);
        privateRadioButton.setSelected(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jdesktop/wonderland/modules/audiomanager/client/resources/Bundle"); // NOI18N
        privateRadioButton.setText(bundle.getString("PrivacyPanel.privateRadioButton.text")); // NOI18N
        privateRadioButton.setName("privateRadioButton"); // NOI18N
        privateRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privateRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(secretRadioButton);
        secretRadioButton.setText(bundle.getString("PrivacyPanel.secretRadioButton.text")); // NOI18N
        secretRadioButton.setName("secretRadioButton"); // NOI18N
        secretRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretRadioButtonActionPerformed(evt);
            }
        });

        privacyDescriptionLabel.setText(bundle.getString("PrivacyPanel.privacyDescriptionLabel.text")); // NOI18N
        privacyDescriptionLabel.setName("privacyDescriptionLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(privateRadioButton)
                        .add(29, 29, 29)
                        .add(secretRadioButton))
                    .add(privacyDescriptionLabel))
                .add(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(secretRadioButton)
                    .add(privateRadioButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(privacyDescriptionLabel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void privateRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privateRadioButtonActionPerformed
        privacyDescriptionLabel.setText(PRIVATE_DESCRIPTION);
    }//GEN-LAST:event_privateRadioButtonActionPerformed

    private void secretRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretRadioButtonActionPerformed
        privacyDescriptionLabel.setText(SECRET_DESCRIPTION);
    }//GEN-LAST:event_secretRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel privacyDescriptionLabel;
    private javax.swing.JRadioButton privateRadioButton;
    private javax.swing.JRadioButton secretRadioButton;
    // End of variables declaration//GEN-END:variables
}
