// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKTools_SequenceNodeOfSequenceOfReturnValue.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _WOKTools_ReturnValue_HeaderFile
#include <WOKTools_ReturnValue.hxx>
#endif
#ifndef _WOKTools_SequenceOfReturnValue_HeaderFile
#include <WOKTools_SequenceOfReturnValue.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(WOKTools_SequenceNodeOfSequenceOfReturnValue)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WOKTools_SequenceNodeOfSequenceOfReturnValue)


IMPLEMENT_DOWNCAST(WOKTools_SequenceNodeOfSequenceOfReturnValue,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WOKTools_SequenceNodeOfSequenceOfReturnValue)


#define SeqItem Handle_WOKTools_ReturnValue
#define SeqItem_hxx <WOKTools_ReturnValue.hxx>
#define TCollection_SequenceNode WOKTools_SequenceNodeOfSequenceOfReturnValue
#define TCollection_SequenceNode_hxx <WOKTools_SequenceNodeOfSequenceOfReturnValue.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKTools_SequenceNodeOfSequenceOfReturnValue
#define TCollection_SequenceNode_Type_() WOKTools_SequenceNodeOfSequenceOfReturnValue_Type_()
#define TCollection_Sequence WOKTools_SequenceOfReturnValue
#define TCollection_Sequence_hxx <WOKTools_SequenceOfReturnValue.hxx>
#include <TCollection_SequenceNode.gxx>

