// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKTools_SequenceOfReturnValue.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _WOKTools_ReturnValue_HeaderFile
#include <WOKTools_ReturnValue.hxx>
#endif
#ifndef _WOKTools_SequenceNodeOfSequenceOfReturnValue_HeaderFile
#include <WOKTools_SequenceNodeOfSequenceOfReturnValue.hxx>
#endif
 

#define SeqItem Handle_WOKTools_ReturnValue
#define SeqItem_hxx <WOKTools_ReturnValue.hxx>
#define TCollection_SequenceNode WOKTools_SequenceNodeOfSequenceOfReturnValue
#define TCollection_SequenceNode_hxx <WOKTools_SequenceNodeOfSequenceOfReturnValue.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKTools_SequenceNodeOfSequenceOfReturnValue
#define TCollection_SequenceNode_Type_() WOKTools_SequenceNodeOfSequenceOfReturnValue_Type_()
#define TCollection_Sequence WOKTools_SequenceOfReturnValue
#define TCollection_Sequence_hxx <WOKTools_SequenceOfReturnValue.hxx>
#include <TCollection_Sequence.gxx>

