// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKBuilder_DataMapIteratorOfDataMapOfMSActionIDOfMSAction.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _WOKBuilder_MSActionID_HeaderFile
#include <WOKBuilder_MSActionID.hxx>
#endif
#ifndef _WOKBuilder_MSAction_HeaderFile
#include <WOKBuilder_MSAction.hxx>
#endif
#ifndef _WOKBuilder_DataMapOfMSActionIDOfMSAction_HeaderFile
#include <WOKBuilder_DataMapOfMSActionIDOfMSAction.hxx>
#endif
 

#define TheKey WOKBuilder_MSActionID
#define TheKey_hxx <WOKBuilder_MSActionID.hxx>
#define TheItem Handle_WOKBuilder_MSAction
#define TheItem_hxx <WOKBuilder_MSAction.hxx>
#define Hasher WOKBuilder_MSActionID
#define Hasher_hxx <WOKBuilder_MSActionID.hxx>
#define WOKTools_DataMapIterator WOKBuilder_DataMapIteratorOfDataMapOfMSActionIDOfMSAction
#define WOKTools_DataMapIterator_hxx <WOKBuilder_DataMapIteratorOfDataMapOfMSActionIDOfMSAction.hxx>
#define WOKTools_DataMap WOKBuilder_DataMapOfMSActionIDOfMSAction
#define WOKTools_DataMap_hxx <WOKBuilder_DataMapOfMSActionIDOfMSAction.hxx>
#include <WOKTools_DataMapIterator.gxx>

