// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WOKBuilder_SequenceOfObjectFile.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _WOKBuilder_ObjectFile_HeaderFile
#include <WOKBuilder_ObjectFile.hxx>
#endif
#ifndef _WOKBuilder_SequenceNodeOfSequenceOfObjectFile_HeaderFile
#include <WOKBuilder_SequenceNodeOfSequenceOfObjectFile.hxx>
#endif
 

#define SeqItem Handle_WOKBuilder_ObjectFile
#define SeqItem_hxx <WOKBuilder_ObjectFile.hxx>
#define TCollection_SequenceNode WOKBuilder_SequenceNodeOfSequenceOfObjectFile
#define TCollection_SequenceNode_hxx <WOKBuilder_SequenceNodeOfSequenceOfObjectFile.hxx>
#define Handle_TCollection_SequenceNode Handle_WOKBuilder_SequenceNodeOfSequenceOfObjectFile
#define TCollection_SequenceNode_Type_() WOKBuilder_SequenceNodeOfSequenceOfObjectFile_Type_()
#define TCollection_Sequence WOKBuilder_SequenceOfObjectFile
#define TCollection_Sequence_hxx <WOKBuilder_SequenceOfObjectFile.hxx>
#include <TCollection_Sequence.gxx>

